import SQLite, { SQLiteDatabase } from 'react-native-sqlite-storage';

// Open the database
const openDatabase = async (): Promise<SQLiteDatabase> => {
  return new Promise((resolve, reject) => {
    const db = SQLite.openDatabase(
      { name: 'MP.db', location: 'default' },
      () => {
        resolve(db); // Renvoie la base de données une fois ouverte
      },
      (error) => {
        reject(error);
      }
    );
  });
};
export const setupDatabase = async (): Promise<string> => {
  console.log("Bubu1");
  const db = await openDatabase();
  console.log("Bubu2");

  db.transaction(tx => {
    
    tx.executeSql(
      'CREATE TABLE IF NOT EXISTS PathType (ID INTEGER NOT NULL UNIQUE, LibelleFR TEXT NOT NULL, LibelleAR TEXT NOT NULL, PRIMARY KEY(ID));',
      [],
      () => {
        console.log("PathType table created.");
      },
      (tx, error) => {
        console.error("Error creating PathType:", error.message);
      }
    );

    console.log("Bubu3");

    tx.executeSql(
      `CREATE TABLE IF NOT EXISTS Path (
        "ID" INTEGER NOT NULL UNIQUE,
        "LibelleFR" TEXT NOT NULL,
        "LibelleAR" TEXT NOT NULL,
        "PathTypeID" INTEGER NOT NULL,
        FOREIGN KEY("PathTypeID") REFERENCES "PathType"("ID"),
        PRIMARY KEY("ID"));`,  // Fix the closing parenthesis here
      [],
      () => {
        console.log("Path table created.");
      },
      (tx, error) => {
        console.error("Error creating Path:", error.message);
      }
    );

    tx.executeSql(
      `CREATE TABLE IF NOT EXISTS PathTab (
        "IDPath" INTEGER NOT NULL,
        "NTAB" TEXT NOT NULL,
        FOREIGN KEY("IDPath") REFERENCES "Path",
        PRIMARY KEY("IDPath", "NTAB")
      );`,
      [],
      () => {
        console.log("PathTab table created.");
      },
      (tx, error) => {
        console.error("Error creating PathTab:", error.message);
      }
    );

    tx.executeSql(
      `CREATE TABLE IF NOT EXISTS Agents (
        "ID" INTEGER NOT NULL UNIQUE,
        "LibelleFR" TEXT NOT NULL,
        "LibelleAR" TEXT NOT NULL,
        "NTAB" TEXT,
        PRIMARY KEY("ID")
      );`,
      [],
      () => {
        console.log("Agents table created.");
      },
      (tx, error) => {
        console.error("Error creating Agents:", error.message);
      }
    );

    console.log("Bubu5");

    // Retrieve and log all table names
    tx.executeSql(
      "SELECT name FROM sqlite_master WHERE type='table';",
      [],
      (tx, results) => {
        for (let i = 0; i < results.rows.length; i++) {
          console.log("Table Name:", results.rows.item(i).name);
        }
      },
      (tx, error) => {
        console.error("Error fetching table names:", error.message);
      }
    );


    console.log("dudu")})
    db.transaction(tx => {
    // Check if PathType table is empty
     tx.executeSql(
    'SELECT COUNT(*) AS count FROM PathType',
    [],
    (tx, results) => { console.log("A")
      if (results.rows.item(0).count === 0) {
       
        // If empty, insert default values
        tx.executeSql(
          `INSERT INTO PathType (LibelleFR, ID, LibelleAR) VALUES
('Pathologies broncho-pulmonaires, pleurales', 1, 'أمراض الجهاز التنفسي والجنبي'),
('Pathologies ophtalmologiques, ORL et stomatologiques', 2, 'أمراض العيون والأنف والأذن والحنجرة والأسنان'),
('Cancers', 3, 'السرطانات'),
('Pathologies cutanéo-muqueuses', 4, 'أمراض الجلد والأغشية المخاطية'),
('Pathologies infectieuses et parasitaires', 5, 'الأمراض المعدية والطفيليات'),
('Pathologies rénales, vésicales et génitales', 6, 'أمراض الكلى والمثانة والأعضاء التناسلية'),
('Pathologies hématologiques', 7, 'أمراض الدم'),
('Pathologies cardio-vasculaires', 8, 'أمراض القلب والأوعية الدموية'),
('Pathologies neurologiques et psychiatriques', 9, 'الأمراض العصبية والنفسية'),
('Intoxications', 10, 'التسممات'),
('Pathologies hépatho-gastro-intestinales', 11, 'أمراض الكبد والجهاز الهضمي'),
('Pathologies ostéoarticulaires', 12, 'أمراض العظام والمفاصل'),
('Pathologies auto-immunes', 13, 'الأمراض المناعية الذاتية'),
('Pathologies diverses', 14, 'أمراض متنوعة'),
('Pathologies endocriniennes', 15, 'أمراض الغدد الصماء');`,
          [],
          () => {
            console.log("Default values inserted into PathType.");
          },
          (tx, error) => {
            console.error("Error inserting values into PathType:", error.message);
          }
        );
      }
    },
    (tx, error) => {
      console.error("Error checking PathType count:", error.message);
    }
  );


    console.log("Bubu7");})
    db.transaction(tx => {
      // Vérification et insertion dans Path
      tx.executeSql('SELECT COUNT(*) AS count FROM Path', [], (tx, results) => {
        console.log("B")
        if (results.rows.item(0).count === 0) {console.log('DUDU1');
          tx.executeSql(`INSERT INTO Path (LibelleFR,ID,PathTypeID,LibelleAR) VALUES
          ('Accès confusionnels',1,9,'نوبات اختبال'),
          ('Accidents aigus',2,9,'الحوادث الحادة'),
          ('Accidents nerveux aigus',3,9,'حوادث عصبية حادة'),
          ('Acné',4,4,'حب الشباب (العد)'),
          ('Acouphènes',5,2,'الإحساس السمعي المرضي'),
          ('Acrodermatite papuleuse (hépatite à virus B)',6,4,'التهاب جلد الأطراف الحطاطي'),
          ('Adénocarcinome hépatocellulaire',7,3,'سرطان غدي لخلايا الكبد'),
          ('Adénopathie (brucellose chronique)',8,5,'تضخم الغدد اللمفية'),
          ('Affections des voies aériennes',9,1,'الاعتلالات بالمجاري التنفسية'),
          ('Amaurose',10,2,'كمنة'),
          ('Amblyopie',11,2,'غمش'),
          ('Amnésie',12,9,'فقدان الذاكرة'),
          ('Anémie',13,5,'فقر الدم'),
          ('Anémie de type hémolytique',14,7,'فقر الدم الانحلالي'),
          ('Anémie hémolytique (hépatite à virus B)',15,7,'فقر الدم الانحلالي  (التهاب الكبد بفيروس B)'),
          ('Anémie, leucopénie, thrombopénie ou syndrome hémorragique consécutifs à une irradiation aiguë',16,7,'فقر الدم و قلة الكريات البيضاء و قلة الصفيحات أو متلازمة نزفية ناتجة عن إشعاعات حادة'),
          ('Anémie, leucopénie, thrombopénie ou syndrome hémorragique, consécutifs à une irradiation chronique',17,7,'فقر الدم و قلة الكريات البيضاء و قلة الصفيحات أو متلازمة نزفية ناتجة عن إشعاعات مزمنة'),
          ('Anémies hémolytiques',18,7,'فقر الدم الانحلالي ذو الحدوث المفاجئ'),
          ('Angiosarcome',19,3,'الغرن الوعائي'),
          ('Angiosarcome du foie',20,3,'الغرن الوعائي الكبدي'),
          ('Anxiété pantophobique',21,9,'قلق رهابي شامل'),
          ('Aphasie',22,9,'الحبسة'),
          ('Aphasie et dysarthrie',23,9,'الحبسة و الرتة'),
          ('Aplasies ou hypoplasies médullaires entraînant: anémies, leucopénies, neutropénies',24,7,'نقص أو خلل التنسج النقوي الذي يؤدي إلى : فقر الدم, نقص الكريات البيضاء, نقص الكريات البيضاء ذات الحبيبات الناصلة (نقص الكريات العدلة)'),
          ('Arachnoïdite (brucellose chronique)',25,9,'التهاب العنكبوتية'),
          ('Arrêt circulatoire (intoxication aigue)',26,10,'توقف الدورة الدموية (التسمم الجاد)'),
          ('Artérite des membres inferieurs (intoxications chroniques)',27,8,'التهاب شرايين الساقين'),
          ('Arthrite chronique destructive (borréliose de Lyme)',28,2,'التهاب مفصلي مزمن مخرب'),
          ('Arthrite séreuse ou suppurée (brucellose chronique)',29,2,'التهاب مفصلي مصلي أو قيحي'),
          ('Arthrose du coude',30,2,'فصال المرفق'),
          ('Asbestose',31,11,'سحار الأسبست'),
          ('Aspergillose intracavitaire (complication)',32,5,'داء الرشاشيات داخل الأجواف المثبت بتحليل مصلي'),
          ('Asthénie',33,9,'وهن'),
          ('Asthénie profonde associée ou non à un syndrome dépressif (brucellose chronique)',34,9,'وهن عميق مرتبط أو غير مرتبط بمتلازمة اكتآبية'),
          ('Asthme',35,1,'ربو'),
          ('Ataxie',36,9,'الهزع'),
          ('Ataxie Cérébelleuse',37,9,'رنح مخيخي'),
          ('Atteinte des nerfs périphériques et crâniens (syndrome de Garin-Bujadoux-Bannwarth)',38,9,'إصابات الأعصاب الطرفية و الجمجمية (متلازمة غارن و بوجادو ز بانوراث)'),
          ('Atteinte inflammatoire des tissus sous-cutanés des zones d''appui du coude',39,2,'إصابة التهابية للأنسجة الجلدية التحتية بمناطق الارتفاق'),
          ('Atteinte inflammatoire des tissus sous-cutanés des zones d''appui du genou',40,2,'إصابات التهابية للأنسجة الجلدية التحتية بمناطق الضغط بالركبة'),
          ('Atteinte vasculaire cubito-palmaire (Syndrome du marteau hypothénar)',41,8,'إصابة عرقية زندية راحية في حانب واحد عادة (متلازمة مطرقة الضرة) تؤدي إلى ظاهرة راينود أو مظاهر إقفارية بالأصابع'),
          ('Atteintes viscérales (staphylococcie)',42,5,'إصابات في الأحشاء'),
          ('Blépharite',43,2,'التهاب الجفن'),
          ('Blépharite (effets caustiques)',44,2,'التهاب الأجفان (التأثيرات الكاوية)'),
          ('Blépharo-conjonctivite récidivante',45,2,'الالتهابات المتكررة بالجفن و الملتحمة'),
          ('Bradycardie',46,8,'بطء نبض القلب'),
          ('Bronchite',47,1,'التهاب قصبي'),
          ('Broncho-alvéolite aigue ou subaigue avec signes généraux',48,1,'التهاب قصبي حاد أو شبه حاد مرفوق بعلامات عامة'),
          ('Bronchoalvéolite aigue ou subaigue avec syndrome respiratoire (dyspnée, toux, de moisissures ou à des expectoration) et/ou signes actinomycètes contaminant les généraux (fièvre, particules végétales ou animales amaigrissement)',49,1,'الالتهاب القصبي السنخي الحاد أو شبه الحاد مع متلازمة تنفسية (ضيق تنففس و سعال و نفث)'),
          ('Broncho-pneumonie (pneumococcie)',50,1,'التهاب قصبي رئوي'),
          ('Broncho-pneumonie (streptococcie)',51,1,'التهابات قصبية رئوية'),
          ('Bronchopneumopathie aigue',52,1,'التهاب قصبي رئوي حاد'),
          ('Broncho-pneumopathie aigue ou subaigue diffuse',53,1,'اعتلال قصبي رئوي حاد أو شبه حاد منتشر'),
          ('Broncho-pneumopathie chronique obstructive',54,1,'الاتهاب القصبي الرئوي المزمن و الانسدادي و المترتب عن نوبات تنفسية انسدادية حادة'),
          ('Broncho-pneumopathie chronique obstructive entraînant un déficit respiratoire chronique',55,1,'الاتهاب القصبي الرئوي المزمن الانسدادس المؤدي إلى عجز مزمن في التنفس'),
          ('Bronchopneumopathies aigues',56,1,'التهابات قصبية رئوية حادة'),
          ('Brûlures chimiques',57,4,'الحروق الكيماوية'),
          ('Brûlures et irritations cutanées',58,4,'الحروق و التهيجات الجلدية'),
          ('Brûlures oculaires et conjonctivite',59,2,'الحروق البصرية و التهاب الملتحمة'),
          ('Cancer bronchique primitif',60,1,'سرطان بدائي بالقصبات الهوائية'),
          ('Cancer broncho-pulmonaire primitif',61,1,'سرطان قصبي رئوي بدائي'),
          ('Cancer des cavités nasales',62,2,'سرطان التجاويف الأنفية'),
          ('Cancer des voies urinaires',63,3,'سرطان المسالك البولية'),
          ('Cancer primitif de l''ethmoïde et des sinus de la face',64,3,'سرطان بدائي بالعظم المصفوي و جيوب الوجه'),
          ('Cancer primitif: carcinome des fosses nasales, de l''ethmoide et des autres sinus de la face',65,3,'سرطان بدائي : سرطان غدي في المناخر و في العظم الغربالي و بجيوب الوجه'),
          ('Carcinome du nasopharynx',66,3,'سرطان البلعوم الأنفي'),
          ('Carcinome hépato-cellulaire (hépatite à virus B)',67,3,'سرطان غدي كبدي خلوي (التهاب الكبد بفيروس B)'),
          ('Carcinome hépato-cellulaire (hépatite à virus C)',68,3,'سرطان غدي كبدي خلوي (التهاب الكبد بفيروس C)'),
          ('Carcinomes cutanés baso-cellulaires ou spino-cellulaires',69,3,'سرطان غدي جلدي ذو خلايا قاعدية أو حرشفية'),
          ('Cardiopathie ischémique (intoxications chroniques)',70,8,'مرض القلب الإقفاري'),
          ('Cataracte',71,2,'الساد'),
          ('Céphalées',72,9,'صداع'),
          ('Charbon gastro-intestinal',73,11,'مرض الفحم بالمعدة و الأمعاء'),
          ('Charbon pulmonaire',74,1,'مرض الفحم بالرئة'),
          ('Cirrhose (hépatite à virus C)',75,11,'تليف الكبد'),
          ('Coliques et diarrhées',76,11,'مغص و إسهال'),
          ('Coma',77,9,'غيبوبة'),
          ('Complications articulaires (gonocoques)',78,5,'مضاعفات مفصلية'),
          ('Confusion mentale',79,9,'خلط ﺫهني'),
          ('Conjonctivite',80,2,'التهاب الملتحمة'),
          ('Conjonctivite aigue bilatérale',81,2,'التهاب الملتحمة الحاد الثنائي'),
          ('Conjonctivite chronique',82,2,'التهاب الملتحمة المزمن أو التهاب الجفن و الملتحمة المزمن'),
          ('Conjonctivite folliculaire avec ou sans participation cornéenne',83,2,'التهاب الملتحمة جريبي مع أو بدون إصابة قرنية '),
          ('Conjonctivite hémorragique',84,2,'التهاب نزفي للملتحمة'),
          ('Conjonctivite oedémateuse avec chémosis',85,2,'التهاب الملتحمة الودمية مع انسلال استسقائي'),
          ('Conjonctivite récidivante en cas de nouvelle exposition',86,2,'التهاب الملتحمة المتكرر في حالة التعرض من جديد للخطر و المتبث باختبار'),
          ('Conjonctivites aigues ou récidivantes',87,2,'التهابات حادة أو متكررة بالملتحمة'),
          ('Conjontivites photo-toxiques',88,2,'التهاب الملتحمة المستثارة بالتعرض للأشعة الضوئية السامة'),
          ('Constipation',89,11,'قبض'),
          ('Crampes abdominales',90,11,'أمغاص البطن'),
          ('Crises épileptiformes',91,9,'أزمات صرعية'),
          ('Crises épileptiques (accidents aigus)',92,9,'نوبات صرعية'),
          ('Cyanose',93,8,'زرقان'),
          ('Dégénéréscence maligne broncho-pulmonaire compliquant les lésions parenchy- mateuses et pleuralesbénignes',94,3,'تلف قصبي رئوي خبيث يعقد الإصابات الحشوية و الجنوبية الحميدة'),
          ('Dépression mélancolique',95,9,'اكتئاب سوداوي'),
          ('Dermite aigue irritative ou eczématiforme',96,4,'التهاب الجلد الحاد التهيجي أو الاكزيمي الشكل'),
          ('Dermite chronique atrophiante (borréliose de Lyme)',97,4,'التهاب جلدي مزمن يسبب ضمورا'),
          ('Dermite chronique irritative ou eczématiforme',98,4,'التهاب الجلد المزمن التهيجي أو الاكزيمي الشكل'),
          ('Dermite de contact orthoergique (effets caustiques)',99,4,'الالتهابات الجلدية التهييجية الناتجة عن ملامسة المادة (التأثيرات الكاوية)'),
          ('Dermite d''irritation (effets caustiques)',100,4,'التهاب تهييجي بالأنف (التأثيرات الكاوية)'),
          ('Dermites',101,4,'التهابات الجلد'),
          ('Dermites chroniques irritatives ou eczématiformes',102,4,'التهابات جلدية مزمنة تهييجية أو إكزيمية الشكل'),
          ('Dermites chroniques ou récidivantes',103,4,'الالتهابات الجلدية المزمنة أو المتكررة'),
          ('Dermites eczématiformes',104,4,'الالتهابات الجلدية الاكزيمية الشكل'),
          ('Dermites irritatives',105,4,'التهابات جلدية تهييجية'),
          ('Dermites irrititatives ou eczématiformes récidivant en cas de nouvelle exposition au risque',106,4,'التهابات جلدية حادة أو متكررة بعد التعرض من جديد للخطر'),
          ('Dermites Photo-toxiques',107,4,'الالتهابات الجلدية المستثارة بالتعرض للأشعة الضوئية السامة'),
          ('Dermites, conjonctivites irritatives',108,4,'التهابات جلدية, التهابات الملتحمة التهييجية'),
          ('Diabète',109,15,'داء السكري'),
          ('Diarrhées',110,11,'الإسهال'),
          ('Diarrhées (intoxication aigue)',111,10,'إسهال (التسمم الحاد)'),
          ('Diplopie',112,2,'شفع'),
          ('Douleurs abdominales (intoxication aigue)',113,10,'آلام في البطن (التسمم الحاد)'),
          ('Douleurs précordiales à type d''angine de poitrine',114,8,'آلام أماقلبية كالذبحة الصدرية'),
          ('Douleurs radiculaires (borréliose de Lyme)',115,9,'آلام جدرية'),
          ('Dyskératose lenticulaire en disue (maladie de Bowen)',116,4,'خلل تقرن بالبشرة عدسي الشكل (مرض بوين)'),
          ('Dyskératoses palmo-plantaires (intoxication subaigue)',117,10,'خلل تقرن راحة اليد و باطن القدم'),
          ('Dyspnée aigue',118,1,'ضيق التنفس الحاد'),
          ('Dyspnée asthmatiforme',119,1,'ضيق تنفسي ربوي الشكل'),
          ('Emphysème',120,1,'انتفاخ الرئة'),
          ('Encéphalite (complications de la varicelle)',121,9,'التهاب الدماغ'),
          ('Encéphalo-myélite progressive (borréliose de Lyme)',122,9,'التهاب دماغي نخاعي متصاعد'),
          ('Encéphalopathie aigue',123,9,'اعتلال دماغي حاد'),
          ('Encéphalopathie aigue associant au moins deux des signes suivants: hallucinations; déficit moteur ou sensitif d''origine centrale; amaurose; coma; convulsions',124,9,'اعتلال دماغي حاد يشمل على الأقل اثنين من العلامات التالية : هذيان, عجز حركي أو حسي مركزي الأصل , كمنة ( عمى جزئي أو كلي), غيبوبة, اختلاجات'),
          ('Encéphalopathie chronique (trois des cinq anomalies suivantes): ralentissement psychomoteur; altération de la dextérité; déficit de la mémoire épisodique; troubles des fonctions exécutives; diminution de l''attention  et ne s''aggravant pas après cessation de l''exposition au risque',125,9,'اعتلال دماغي مزمن (ثلاتة من التشوهات الخمس التالية): تخلف نفسي حركي, ضعف المهارة, عجز الذاكرة العرضية, اضطرابات الوظائف التنفيذية, انخفاض اليقظة, و لايتفاقم بعد التوقف عن التعرض للخطر'),
          ('Encéphalopathies caractérisées par des altérations des fonctions cognitives, constituées par au moins trois des six anomalies suivantes: ralentissement psychomoteur ; troubles de la dextérité, de la mémoire, de l''organisation visuospatiale,des fonctions exécutives, de l''attention, et ne s''aggravant pas après cessation de l''exposition au risque',126,9,'اعتلالات دماغية تتميز باختلالات في الوظائف المعرفية, و تتألف من ثلاثة على الأقل من التشوهات الستة التالية: تخلف نفسي حركي, اضطرابات في المهارة و في الذاكرة و في التنظيم البصري المكاني و في الوظائف التنفيذية و في اليقظة و التي لا تتفاقم بعد التوقف عن التعرض للخطر'),
          ('Endocardite',127,5,'التهاب الشغاف'),
          ('Epaississement de la plèvre viscérale, soit diffus soit localisé',128,1,'تتخن غشاء الجنب الحشوي سواء كان موضعيا أو منتشرا'),
          ('Epicondylite du coude',129,2,'التهاب اللقيمة'),
          ('Epididymite (brucellose chronique)',130,5,'التهاب البربخ'),
          ('Epithélioma cutané primitif',131,3,'الورم الظهاري الجلدي البدائي'),
          ('Épitrochléite du coude',132,2,'التهاب البكيرة'),
          ('Erysipèle (streptococcie)',133,5,'حميرة'),
          ('Erythème migrant de Lipschutz (borréliose de Lyme)',134,4,'حمامي لبشوتس'),
          ('Erythème noueux (hépatite à virus B)',135,4,'حمامي عقدية  (التهاب الكبد بفيروس B)'),
          ('Erythème noueux (hépatite à virus C)',136,4,'حمامي عقدية (التهاب الكبد بفيروس C)'),
          ('Fibrose pulmonaire',137,1,'تليف رئوي'),
          ('Fibrose pulmonaire diffuse avec troubles fonctionnels et signes généraux ( amaigrissement, fatigue), les complications cardiaques ( insuffisance ventriculaire droite) et les complications pleuropulmonaires secondaires (pneumothorax spontané)',138,1,'تليف رئوي منتشر مع وجود اضطرابات وظيفية و علامات عامة ( نحول و وهن) بما في ذلك المضاعفات القلبية (عجز البطين الأيمن) و المضاعفات الجنوبية الرئوية الثانوية (استرواح الصدر العفوي)'),
          ('Fibrose pulmonaire diffuse et ses complications: infection pulmonaire, insuffisance ventriculaire droite',139,1,'تليف رئوي منتشر و مضاعافاته: تعفن رئوي, عجز البطين الأيمن'),
          ('Fièvre ondulante sudoro-algique (brucellose aigue avec septicémie)',140,5,'حمى متموجة تعرقية مؤلمة'),
          ('Fissuration ou rupture du ménisuqe (complications)',141,2,'تشقق أو تمزق الغضروف المفصلي (مضاعفات)'),
          ('Formes à rechute (hépatite à virus A)',142,11,'الأشكال الانتكاسية'),
          ('Formes génitales subaiguës (brucellose subaigue avec focalisation)',143,5,'إصابات تناسلية شبه حادة'),
          ('Formes hépato-spléniques subaigues (brucellose subaigue avec focalisation)',144,5,'إصابات شبه حادة بالكبد و الطحال'),
          ('Formes neuroméningées',145,9,'أشكال عصبية سحائية'),
          ('Formes typhoïdes avec troubles digestifs et états stuporeux',146,5,'أشكال من حمى تيفية مع اضطرابات هضمية و حالات ذهول'),
          ('Gale avec prurit et surinfections des atteintes cutanées',147,5,'جرب مصحوب بحكة شديدة و أحيانا يتضاعف التعفن في الأماكن الجلدية المصابة بالطفيلي'),
          ('Glomérulonéphrite aigue (streptococcie)',148,6,'التهاب كبيبات الكلي الحاد'),
          ('Gonococcie cutanée',149,5,'داء المكورات البنية الجلدية'),
          ('Granulome cutané avec réaction gigantofolliculaire',150,4,'ورم حبيبي جلدي كع تفاعل جريبي متعملق'),
          ('Graphitose',151,1,'سحار غرافيتي'),
          ('Hémoglobinurie',152,7,'تواجد الخضاب الدموي في البول - بيلة هيموغلوبينية'),
          ('Hémorragie (brucellose chronique)',153,7,'نزيف'),
          ('Hépatite',154,5,'التهاب كبدي'),
          ('Hépatite (brucellose chronique)',155,11,'التهاب الكبد'),
          ('Hépatite aigue (Co-infection d''une hépatite B par le virus D)',156,11,'التهاب الكبد الحاد مع أو بدون مظاهر يرقانية (العدوى المشتركة بفيروس التهاب الكبد B مع فيروس D)'),
          ('Hépatite aigue (Hépatite à virus C)',157,11,'التهاب الكبد الحاد (التهاب الكبد بفيروس C)'),
          ('Hépatite aiguë avec ou sans manifestations ictériques (hépatite à virus B)',158,11,'التهاب الكبد الحاد مع أو بدون مظاهر يرقانية'),
          ('Hépatite aigue ou subaigue (hépatite à virus A)',159,11,'التهاب الكبد الحاد أو شبه الحاد (التهاب الكبد بفيروس A)'),
          ('Hépatite aigue ou subaigue (hépatite à virus E)',160,11,'التهاب الكبد الحاد أو شبه الحاد (التهاب الكبد بفيروس E)'),
          ('Hépatite chronique active (Co-infection d''une hépatite B par le virus D)',161,11,'التهاب الكبد المزمن نشيط أو غير نشيط'),
          ('Hépatite chronique active ou non (hépatite à virus B)',162,11,'التهاب الكبد المزمن نشيط أو غير نشيط  (التهاب الكبد بفيروس B)'),
          ('Hépatite cytolytique (intoxication aigue)',163,10,'التهاب الكبد المدمر (التسمم الحاد)'),
          ('Hépatite fulminante (Co-infection d''une hépatite B par le virus D)',164,11,'التهاب الكبد الصاعق (العدوى المشتركة بفيروس التهاب الكبد B مع فيروس D)'),
          ('Hépatite fulminante (hépatite à virus B)',165,11,'التهاب الكبد الصاعق  (التهاب الكبد بفيروس B)'),
          ('Hépatite fulminante (hépatite à virus E)',166,11,'التهاب الكبد الصاعق (التهاب الكبد بفيروس E)'),
          ('Hépatites aigues cytolytique',167,11,'التهابات الكبد الحادة المدمرة للخلايا'),
          ('Hépatites amibiennes',168,11,'التهاب الكبد الأميبي'),
          ('Hépatonéphrite',169,6,'اعتلال كلوي كبدي غير حمي في بدايته و يكون يرقانيا أو غير يرقاني'),
          ('Hépatonéphrite initialement apyrétique, ictérigène ou non',170,6,'التهاب كلوي كبدي غير حمي في بدايته و يكون يرقانيا أو غير يرقاني'),
          ('Hygroma aigu des bourses séreuses du coude',171,2,'الالتهابات الحادة بالأجربة المصلية'),
          ('Hygroma aigu des bourses séreuses du genou',172,2,'الالتهابات الحادة بالأجربة المصلية بالركبة'),
          ('Hygroma chronique des bourses séreuses du coude',173,2,'الالتهابات المزمنة بالأجربة المصلية'),
          ('Hygroma chronique des bourses séreuses du genou',174,2,'الالتهابات المزمنة بالأجربة المصلية بالركبة'),
          ('Hyperacousie',175,2,'فرط السمع'),
          ('Hypersalivation',176,11,'سيلان اللعاب المفرط'),
          ('Hypertension artérielle (intoxications chroniques)',177,10,'ارتفاع الضغط الدموي'),
          ('Hypoacousie de perception par lésion cochléaire irréversible',178,2,'نقص السمع الإدراكي'),
          ('Hypoacousie par lésion cochléaire irréversible',179,2,'ضعف السمع مع إصابة قوقعية غير قابلة للعلاج'),
          ('Hypoplasies et aplasies médullaires isolées ou associées (anémie, leucopénie,thrombopénie) acquises primitives non réversibles',180,7,'نقص أوخلل التنسج النقوي معزولا أو مشتركا (فقر الدم, قلة الكريات البيضاء, قلة الصفيحات) و مكتسبا بدائيا و غير قابل للإرتداد'),
          ('Hypotension',181,8,'انخفاض الضغط الشرياني'),
          ('Ictère',182,11,'يرقان'),
          ('Ictère avec hémolyse',183,7,'يرقان و تفتت كريات الدم الحمراء'),
          ('Infarctus du myocarde',184,8,'احتشاء عضلة القلب'),
          ('Infection cutanée granulomateuse ulcéreuse prolongée (Mycobacterium marinum et foruitum)',185,5,'التعفن الجلدي الجبيبومي التقرحي المديد'),
          ('Inflammation périunguéale, douloureuse, d''origine infectieuse, accompagnée ou non de modifications de l''ongle telles que fissurations, striations. dentelures du bord libre, coloration brunâtre, onycholyse (périonyxis et onyxis)',186,4,'التهاب مؤلم حول الظفر ﺫو مصدر تعفني يكون مصحوبا أو غير مصحوب بتغيرات في الظفر مثل تشقق الظفر و تخططه و تسننه و اصطباغه باللون الأسمر و تفسخ الظفر'),
          ('Insuffisance circulatoire (intoxication aigue)',187,10,'قصور الدورة الدموية (التسمم الحاد)'),
          ('Insuffisance rénale aigue (hantavirus)',188,6,'فشل كلوي حاد'),
          ('Insuffisance rénale aigue associée ou précédée par un syndrome dysentérique (intoxication aigue)',189,10,'فشل كلوي حاد مرتبط أو مسبوق بمتلازمة زحارية (التسمم الحاد)'),
          ('Insuffisance respiratoire aigue',190,1,'عجز تنفسي حاد'),
          ('Insuffisance respiratoire chronique caractérisée',191,1,'عجز في التنفس مزمن و مثبت'),
          ('Insuffisance respiratoire chronique obstructive secondaire à la maladie asthmatique',192,1,'عجز تنفسي مزمن انسدادي تابع للمرض الربوي'),
          ('Insuffisance respiratoire liée à un granulome pulmonaire',193,1,'عجز تنفسي مرتبط بورم حبيبي رئوي'),
          ('Insuffisance vasculaire cérébrale (intoxications chroniques)',194,9,'نقص تروية الدماغ'),
          ('Insuffisance ventriculaire droite',195,8,'عجز البطين الأيمن'),
          ('Insuffisance ventriculaire droite caractérisée (complication)',196,8,'عجز مثبت بالبطين الأيمن'),
          ('Intoxication aiguë ou subaiguë avec asthénie, amaigrissement rapide, hypersudation suivie d''hyperthermie avec gênerespiratoire',197,10,'تسمم حاد أو شبه حاد مصحوب بوهن و نحول سريع و تعرق مفرط مصحوب بفرط حرارة و ضيق تنفس'),
          ('Intoxication suraiguë avec hyperthermie, œdème pulmonaire, éventuellement atteinte rénale et myocardique',198,10,'تسمم حاد جدا مصحوب بفرط الحرارة و بوذمة رئوية و احتمال إصابات كلوية و عضلية قلبية'),
          ('Irritation des voies aériennes supérieures et conjonctivites',199,1,'تهييج المجاري الهوائية العليا و التهابات الملتحمة'),
          ('Ischémie myocardique aigue',200,8,'نقص حاد في تروية عضلة القلب'),
          ('Kaolinose',201,1,'سحار صلصالي'),
          ('Kératite',202,2,'التهاب القرنية'),
          ('Kératite (effets caustiques)',203,2,'التهاب القرنية (التأثيرات الكاوية)'),
          ('Kératite nummulaire sous épithéliale',204,2,'التهاب القرنية النقدية الشكل تحت الظهاري'),
          ('Kératite superficielle ulcéreuse avec conjonctivite associée',205,2,'الالتهاب السطخي القرحي للقرنية مع التهاب مشترك للملتحمة'),
          ('Laryngite (effets caustiques)',206,2,'التهاب الحنجرة (التأثيرات الكاوية)'),
          ('Lésion de l''oreille interne',207,2,'إصابات الأذن الداخلية'),
          ('Lésions chroniques du ménisque à caractère dégénératif',208,2,'الإصابات المزمنة للغضروف المفصلي ذو سمة انحلالية, مثبتة باختبارات إضافية أو أثناء التدخل العلاجي'),
          ('Lésions eczématiformes',209,4,'إصابات إكزيمية الشكل'),
          ('Lésions nasales: Perforations, ulcérations',210,2,'إصابات الأنف: تقرحات, تخرمات'),
          ('Lésions pleurales bénignes',211,1,'إصابات جنوبية حميدة'),
          ('Lésions pleuro-pneumoconiotiques à type rhumatoïde (syndrome de Calpan-Collinet)',212,1,'إصابات سحارية بذات الجنب من النوع الرثياني ( متلازمة كابلان كولينات)'),
          ('Lésions primitives de l''épithélium vésical: lésions malignes, tumeurs bénignes',213,3,'إصابات بدائية بظهارة المثانة: أورام خبيثة, أورام حميدة'),
          ('Lésoins eczématiformes récidivant en cas de nouvelle exposition au risque',214,4,'إصابات إكزيمية الشكل متكررة بعد التعرض من جديد للخطر أو مثبتة باختبار جلدي سطحي'),
          ('Leucémies',215,3,'ابيضاض الدم'),
          ('Leucémies aigues myéloblastique et lymphoblastique à l''exclusions des leucémies aigues avec des antécédents d''hémopathies',216,3,'ابيضاض الدم الحاد النقوي و اللمفاوي'),
          ('Leucopénie',217,7,'نقص الكريضات'),
          ('Lichen plan (hépatite à virus C)',218,4,'الحزاز الجلدي'),
          ('Localisations viscérales, cutanéo-muqueuses et oculaires (Pseudomonas aeruginosa)',219,5,'إصابات موضعية في الأحشاء, و إضابات موضعية جلدية مخاطية و بصرية'),
          ('Maladie de parkinson',220,9,'مرض باركنسون'),
          ('Manganisme: Troubles nerveux',221,9,'تسمم بالمنغنيز: اضطرابات عصبية'),
          ('Manganisme: Troubles pulmonaires',222,1,'تسمم بالمنغنيز: اضطرابات رئوية'),
          ('Manifestation consécutives à l''intoxication subaigus ou chronique (cyanose, anémie, subictére)',223,10,'مظاهر ناتجة عن التسمم شبه الحاد أو المزمن'),
          ('Manifestations chroniques (Fièvre Q): endocardite, hépatite granulomateuse)',224,5,'التهاب الشغاف, التهاب الكبد الحبيبومي'),
          ('Manifestations cliniques aigues (Frièvre Q)',225,5,'المظاهر السريرية الحادة'),
          ('Manifestations cliniques aigues de pasteurellose par inoculation',226,5,'المظاهر السريرية الحادة للباستوريلا عن طريق الإلقاح'),
          ('Manifestations cutanées d''allergie (brucellose chronique)',227,4,'مظاهر الحساسية بالجلد'),
          ('Manifestations de la poliomyélite antérieure aigue',228,5,'جميع مظاهر شلل الأطفال الأمامية الحادة'),
          ('Manifestations digestives (douleurs abdominales, vomissements, diarrhées)',229,11,'مظاهر بالجهاز الهضمي (آلام البطن و تقيئ و إسهال)'),
          ('Manifestations d''intoxication oxycarbonée',230,10,'مظاهر التسمم بأول أكسيد الكربون'),
          ('Manifestations irritatives des voies aériennes supérieures',231,1,'المظاهر التهيجية بالمجاري التنفسية العليا'),
          ('Manifestations loco-régionales tardives',232,5,'المظاهر الموضعية المحلية المتأخرة'),
          ('Manifestations psychopathologiques (brucellose chronique)',233,9,'مظاهر نفسية مرضية'),
          ('Manifestations respiratoires chroniques',234,1,'أعراض تنفسية مزمنة'),
          ('Mélanodermie (intoxication subaigue)',235,10,'اسوداد الجلد'),
          ('Méningite',236,9,'التهاب السحايا'),
          ('Méningite lymphocytaire (borréliose de Lyme)',237,9,'التهاب سحائي لمفاوي'),
          ('Méningite purulente (pneumococcie)',238,9,'التهاب السحايا القيحي'),
          ('Méningo-Encéphalite (brucellose chronique)',239,9,'التهاب الدماغ و السحايا'),
          ('Mésothéliome malin primitif de la plèvre, du péritoine, du péricarde',240,3,'ورم المتوسطة الخبيث البدائي بالجنبة أو بالصفاق أو بالتامور'),
          ('Monoarthrite aigue fébrile (brucellose subaigue avec focalisation)',241,5,'التهاب أحادي المفصل حاد ز حمي'),
          ('Mycoses de la peau glabre: Lésions érythémato- vésiculeuses et squameuses circinées, appelées encore herpès circiné',242,4,'فطارات الجلد الامرد: إصابات حمامية حويصلية و حرشفية متحلقة, تسمى أيضا سعفة متحلقة'),
          ('Mycoses des orteils: Lésions érythémato- vésiculeuses et squameuses avec fissuration des plis interdigitaux, ou aspect blanc nacré, épaissi de l''épiderme digital ou interdigital, accompagné ou non de décollement, de fissures épidermiques',243,4,'فطارات أصابع القدم: إصابات حمامية حويصلية و حرشفية مع تشقق ثنايا ما بين الأصابع أو صبغة بيضاء لؤلئية المظهر غليظة بجلد الأصابع أو ما بينها مصحوبة أو غير مصحوبة بانفكاك و شقوق جلدية'),
          ('Mycoses du cuir chevelu: Plaques squameuses du cuir chevelu supportant un mélange de cheveux sains et de cheveux cassés courts, accompagnés quelquefois d''une folliculite suppurée (kérion)',244,4,'فطارات فرة الرأس: لوحات حرشفية بفروة الرأس تحتوي خليطا من الشعر السليم و الشعر المنكسر القصير مصحوبة أحيانا بالتهاب الجريبات القيحي (كريون)'),
          ('Myélite radiculaire (brucellose chronique)',245,9,'التهاب عصبي جذري'),
          ('Myoclonies',246,9,'رمع عضلي'),
          ('Myosis',247,9,'تقبض الحدقة'),
          ('Narcose',248,9,'خدر'),
          ('Nausées',249,11,'الغثيان'),
          ('Nausées (intoxication aigue)',250,10,'غثيان (التسمم الحاد)'),
          ('nausées ou vomissements',251,11,'الغثيان و القيء'),
          ('Nécrose cavitaire aseptique d''une masse pseudotumale (complication)',252,14,'النخر الجوفي غير العفن لكتلة شبه ورمية'),
          ('Néphrite (brucellose chronique)',253,6,'التهاب كلوي'),
          ('Néphrite aigue ou subaigue',254,6,'اعتلال كلوي حاد أو شبه حاد'),
          ('Néphrite azotémique',255,6,'التهاب كلوي أزوتيمي'),
          ('Néphropathie avec protéinurie',256,6,'اعتلال كلوي مع بيلة بروتينية'),
          ('Néphropathie glomérulaire',257,6,'اعتلال الكلي الكبيبي'),
          ('Néphropathie glomérulaire membrano-proliférative (hépatite à virus B)',258,6,'التهاب كبيبات الكلي الغشائي التكاثري'),
          ('Néphropathie tubulaire',259,6,'اعتلال الكلي الأنبوبي'),
          ('Néphropathie tubulo-interstitielle',260,6,'اعتلال الكلي الأنبوبي الخلالي'),
          ('Néphropathies tubulaires',261,6,'اعتلالات كلوية أنبوبية'),
          ('Neuropathie périphérique (complications de la varicelle)',262,9,'مرض الأعصاب الطرفي'),
          ('Neuropathie périphérique confirmée par un ralentissement de la conduction nerveuse',263,9,'اعتلال عصبي طرفي'),
          ('Neuropathie périphérique: sensitivomotrice, douloureuse, distale, ascendante (intoxication subaigue)',264,10,'اعتلال الجهاز العصبي المحيطي: حسي و مؤلم و قرصي و تصاعدي'),
          ('Neuropathies optiques rétrobulbaires bilatérales',265,9,'الاعتلالت العصبية البصرية الثنائية خلف المقلة'),
          ('Névrite optique',266,2,'التهاب العصب البصري'),
          ('Névrite ou polynévrite',267,9,'الالتهاب العصبي أو الاتهاب العصبي المتعدد'),
          ('Nystagmus',268,9,'اختلاج المقلة السريع'),
          ('Œdème aigu du poumon',269,1,'وذمة حادة بالرئة'),
          ('Œdème broncho-alvéolaire',270,1,'الوﺫمة القصبية السنخية'),
          ('Œdème malin',271,4,'وذمة خبيثة'),
          ('Œdème pulmonaire',272,1,'الوذمة الرئوية'),
          ('Oligoathrite régressive (borréliose de Lyme)',273,5,'التهاب متناقض ببعض المفاصل'),
          ('Onyxis localisé habituellement au seul gros orteil, caractérisé par les déformations de l''ongle telles que destruction totale ou partielle, épaississement, striations, fissurations, accompagnées d''hyperkératose sous ou péri-unguéal (périonyxis et onyxis)',274,4,'التهاب منبت الظفر يتموضع عادة بإبهام القدم و يتميز بتشوه كالتلف الكلي أو الجزئي و التغلظ و التخطط و التشقق و يكون مصحوبا بتقرن مفرط تحت الظفر أو حوله'),
          ('Orchite (brucellose chronique)',275,5,'التهاب الخصية'),
          ('Ostéite (brucellose chronique)',276,5,'التهاب عظمي'),
          ('Ostéo-arthrite',277,5,'فصال عظمي'),
          ('Ostéolyse des phalanges unguéales des mains',278,2,'نخر عظام السلاميات الظفرية باليدين'),
          ('Ostéomalacie avec ou sans fractures spontanées, accompagnée ou non de manifestations douloureuses',279,2,'تلين العظام مع أو بدون كسور تلقائية و المصحوب أو غير مصحوب بمظاهر مؤلمة'),
          ('Ostéomalacie ou nécrose du maxillaire inférieur',280,2,'تلين أو نخر عظام الفك الأسفل'),
          ('Ostéonécrose du scaphoïde carpien (maladie de Kolher)',281,2,'نخر العظم القاربي الرسغي (مرض كوهلر)'),
          ('Ostéonécrose du semi-lunaire (maladie de Kienbock)',282,2,'نخر العظم نصف الهلالي (مرض "كيابونخ")'),
          ('Ostéoporose avec ou sans atteinte articulaire intéressant l''épaule, la hanche et le genou',283,2,'نخر عظمي مع أو بدون إصابة مفصلية تهم الكتف و الحزام و الركبة'),
          ('Otite moyenne subaiguë ou chronique',284,2,'التهابات الأذن المتوسطة شبه الحاد أو المزمن'),
          ('Otites compliquées (streptococcie)',285,2,'التهابات الأذن المتفاقمة'),
          ('Otites moyennes chroniques',286,2,'التهابات مزمنة بالأذن المتوسطة'),
          ('Otites moyennes subaigues',287,2,'التهابات شبه حادة بالأذن المتوسطة'),
          ('Panaris (staphylococcie)',288,4,'داحس'),
          ('Papulo-pustules multiples et leurs complications fùronculeuses',289,4,'البثرات الحطاطية المتعددة و مضاعفاتها الدملية'),
          ('Perforation de la cloison nasale (effets caustiques)',290,2,'تخرم حاجز الأنف (التأثيرات الكاوية)'),
          ('Péricardite (borréliose de Lyme)',291,5,'التهاب التامور'),
          ('Pharyngite (effets caustiques)',292,2,'التهاب البلعوم (التأثيرات الكاوية)'),
          ('Phénomène de Raynaud (intoxications chroniques)',293,10,'ظاهرة رينود'),
          ('Phlébite (brucellose chronique)',294,5,'التهاب الوريد'),
          ('Plaies arsenicales',295,4,'الجروح الزرنيخية'),
          ('Plaques calcifiées ou non, péricardiques ou pleurales, unilatérales ou bilatérales',296,1,'صفيحات متكلسة أو غير متكلسة, تامورية أو جنوبية أحادية أو ثنائية الجانب'),
          ('Pleurésie exsudative',297,1,'ذات الجنب النضحية'),
          ('Pleurésie séro-fibrineuse ou purulente (brucellose chronique)',298,1,'ذات الجنب المصلية الفبرينية أو القيحية'),
          ('Pneumonie (pneumococcie)',299,1,'التهاب الرئة'),
          ('Pneumopathie',300,1,'اعتلال رئوي'),
          ('Pneumopathie aigue',301,5,'التهاب رئوي حاد'),
          ('Pneumopathie d''hypersensibilité chronique',302,1,'متلازمة الاتهاب المتكرر بالقصبات الهوائية'),
          ('Pneumopathie interstitielle aigue ou subaigue',303,1,'الاعتلال الرئوي الحاد أو شبه الحاد'),
          ('Pneumopathie spécifique (complications de la varicelle)',304,1,'مرض رئوي نوعي'),
          ('Pneumopathies chroniques Mycobacterium avium intracellulare, Mycobacterium kansasii, Mycobacterium xenopi)',305,1,'الاتهاب الرئوي المزمن'),
          ('Pneumothorax spontané (complication)',306,1,'استرواح الصدر العفوي'),
          ('Polyarthrite (brucellose subaigue avec focalisation)',307,5,'التهاب المفاصل المتعدد'),
          ('Polyarthrite (hépatite à virus B)',308,11,'التهاب المفاصل'),
          ('Polyneuropathies ou neuropathies trigéminles',309,9,'اعتلال الأعصاب المتعدد أو الاعتلال العصبي الثلاثي'),
          ('Polynévrite',310,9,'التهاب عصبي'),
          ('Polynévrites et névrites',311,9,'التهاب الأعصاب المتعددة و الالتهابات العصبية مهما كانت درجتها مصحوبة باضطرابات التفاعلات الكهربائية'),
          ('Polynévrites, avec troubles des récations électriques',312,9,'التهاب الأعصاب المتعدد المصحوب باضطرابات التفاعلات الكهربائية'),
          ('Porphyrie cutanée tardive',313,4,'البورفيري الجلدية الآجلة الناتجة عن سادس كلور البنزين و المتميزة بإصابات فقاعية و المستثارة بالتعرض للشمس و المصحوبة بارتفاع اليوروبورفيرين في البول'),
          ('Porphyrie cutanée tardive (hépatire à virus C)',314,11,'البورفيريا الجلدية الآجلة'),
          ('Primo-infection (Mycobactérium tuberculosis, Mycobactérium bovis, Mycobactérium africanum)',315,5,'العدوة الأولية'),
          ('Prostatite (brucellose chronique)',316,5,'التهاب البروستات'),
          ('Ptérygion',317,2,'الظفرة'),
          ('Purpura (brucellose chronique)',318,7,'فرفرية'),
          ('Purpura (hépatite à virus C)',319,7,'فرفرية (التهاب الكبد بفيروس C)'),
          ('purpura thrombopénique (complications de la varicelle)',320,7,'الفرفرية الناتجة عن نقص الصفيحات بالدم'),
          ('Pustule maligne',321,4,'بثرة خبيثة'),
          ('Pyodermites',322,4,'تقيحات الجلد'),
          ('Radiculalgie par hernie discale L2-L3 ou L3-L4 ou L4-L5, avec atteinte radiculaire de topographie concordante',323,9,'ألم بسبب التهاب في عصب الفخد الناتج عن فتق قرصي بين الفقرات القطنية الثانية و الثالثة أو الثالثة و الرابعة أو الرابعة و الخامسة مع إصابة في جذور الأعصاب تكون متطابقة جغرافيا'),
          ('Radiodermites aigues',324,4,'الالتهابات الإشعاعية الحادة بالجلد'),
          ('Radiodermites chroniques',325,4,'الالتهابات الإشعاعية المزمنة بالجلد'),
          ('Radio-épithélite aigue des muqueuses',326,4,'التهاب الظهارة الإشعاعي الحاد بالأغشية المخاطية'),
          ('Radiolésions chroniques des muqueuses',327,4,'الإصابات الإشعاعية المزمنة بالأغشية المخاطية'),
          ('Radionécrose osseuse',328,2,'نخر شعاعي عظمي'),
          ('Rage',329,5,'داء الكلب'),
          ('Réaction méningée (brucellose chronique)',330,9,'تفاعل سحائي'),
          ('Réaction neuroméningée (brucellose subaigue avec focalisation)',331,9,'تفاعل عصبي سحائي'),
          ('Réactions allergiques systémiques telles que urticaire géante, oedème de Quincke, choc anaphylactique',332,4,'طفح جلدي ضخم, وﺫمة "كينك", صدمة العواري, ناتجة عن التعرض للبن النبات (latex)'),
          ('Rhinite',333,2,'التهاب الأنف'),
          ('Rhinite (effets caustiques)',334,2,'التهاب الأنف (التأثيرات الكاوية)'),
          ('Rhinite récidivant en cas de nouvelle exposition',335,2,'التهاب الأنف المتكرر في حالة تعرض جديد للخطر أو المثبت باختبار'),
          ('Rhinite récidivante',336,2,'التهاب الأنف المتكرر'),
          ('Rickettsioses (manifestations cliniques aigues)',337,5,'داء الريكتسيات'),
          ('Rupture partielle ou transfixiante de la coiffe des rotateurs ',338,2,'تمزق جزئي أو كلي لغطاء العضلات المدورة'),
          ('Sacrocoxite (brucellose chronique)',339,5,'التهاب الأقراص'),
          ('Salpingite (brucellose chronique)',340,5,'التهاب النفير'),
          ('Sarcome osseux',341,3,'غرن عظمي'),
          ('Sciatique par hernie discale L4-L5 ou L5-S1 avec atteinte radiculaire de topographie concordante',342,9,'ألم النسا القطني نتيجة فتق قرصي بين الفقرات القطنية الرابعة و الخامسة أو بين الفقرة القطنية الخامسة و فقرة العجز الأولى مع إصابة في جذور الأعصاب تكون متطابقة طبوغرافيا'),
          ('Sclérodermie systémique progressive',343,13,'التصلب الجلدي النسقي المتطور'),
          ('Sépticémie',344,5,'تعفن الدم'),
          ('Sidérose : pneumopathie interstitielle chronique',345,1,'السحار الحديدي'),
          ('Silicose aigue',346,1,'السحار السيليسي الحاد'),
          ('Silicose chronique ',347,1,'السحار السيليسي المزمن'),
          ('Somnolence',348,9,'وسن'),
          ('Spondylodiscite (brucellose chronique)',349,5,'التهاب الفقرات'),
          ('Stibiose',350,1,'سحار الإثمد (الكحل)'),
          ('Stomatite',351,2,'التهاب فموي'),
          ('Stomatite (effets caustiques)',352,4,'التهاب الفم'),
          ('Subictère',353,11,'يرقان خفيف'),
          ('Surinfection ou suppuration bactérienne broncho-pulmonaire subaiguë ou chronique (complication)',354,1,'تعفن أو تقيح جرثومي قصبي رئوي شبه حاد أو مزمن'),
          ('Syndrome aigu neuro-digestif: vomissements, gastralgies violentes, diarrhées avec délire et céphalée intense',355,11,'متلازمة عصبية حادة تظهر من خلال التقيئ و الآلام العنيفة بالمعدة و الإسهال مع الهذيان و الصداع الشديد'),
          ('Syndrome algique pseudo-grippal (hantavirus)',356,5,'متلازمة آلام شبيهة بالأنفلونزا'),
          ('Syndrome biologique: Neutropénie franche',357,7,'متلازمة بيولوجية متميزة بقلة واضحة للعدلات'),
          ('Syndrome bronchique récidivant',358,1,'متلازمة الالتهاب المتكررة بالقصبات الهوائية'),
          ('Syndrome de compression du nerf sciatique poplité externe',359,2,'متلازمة انضغاط عرق النسا بالمأبض الخارجي'),
          ('Syndrome de la gouttière épitrochléo-olécrânienne (commpression du nerf cubital)',360,9,'متلازمة أخدود البكيرة الزجية (انضغاط العرق الزندي)'),
          ('Syndrome de la loge de Guyon',361,9,'متلازمة حيز "قويون"'),
          ('Syndrome de Raynaud (hépatite à virus B)',362,11,'متلازمة رينود  (التهاب الكبد بفيروس B)'),
          ('Syndrome de Raynaud (hépatite à virus C)',363,11,'متلازمة رينود (التهاب الكبد بفيروس C)'),
          ('Syndrome d''hypertension portale',364,11,'فرط ضغط الدم البابي'),
          ('Syndrome douloureux abdominal apyrétique',365,11,'متلازمة بطنية مؤلمة بدون حمى'),
          ('Syndrome du canal carpien',366,9,'متلازمة القناة الرسغية'),
          ('Syndrome dysentérique',367,10,'متلازمة زحارية'),
          ('Syndrome ébrieux ou narcotique',368,10,'متلازمة اتثمال أو تخدر يمكن أن تؤدي إلى الغيبوبة'),
          ('Syndrome hémorragique (hantavirus)',369,5,'مظاهر نزفية'),
          ('Syndrome ostéo-ligamentaire douloureux ou non, comportant nécessairement une ostéo-condensation diffuse et associée à des calcifications des ligaments sacro-sciatiques ou des membranes interosseuses, radiocubitale ou obturatrice',370,2,'متلازمة مؤلمة و غير مؤلمة بالعظام و الأربطة المفصلية تحتوي بالضرورة على تكثف عظمي منتشر و مرتبطة بتكلس الأربطة العجزية النسوية أو الأغشية الرابطة بين الكعبرة و الزند أو الرابط السدادي'),
          ('Syndrome pouvant revêtir soit l''aspect ou en partie, d''une des grandes formes cliniques (brachiale, oculaire pharyngée, pulmonaire ou thyroïde), ou aspect atypique',371,14,'متلازمة يمكن أن تظهر جزئيا أو كليا إما بإحدى الأشكال السريرية الكبرى (العضدية, الحدقية البلعومية الرئوية, أو الدرقية) أو بشكل غير نمطي'),
          ('Syndrome pseudo-grippal (brucellose aigue avec septicémie)',372,5,'شبه زكام'),
          ('Syndrome respiratoire avec dyspnée, toux, expectoration récidivant après nouvelle exposition',373,1,'متلازمة تنفسية مع ضيق تنفس و سعال و نفث متكررة بعد التعرض من جديد للخطر'),
          ('Syndrome respiratoire irritatif à type de toux et de dyspnée récidivant après nouvelle exposition au risque',374,1,'متلازمة تنفسية تهييجية على شكل سعال و ضيق التنفس متكررة بعد التعرض من جديد للخطر'),
          ('Syndrome respiratoire obstructif aigu',375,1,'متلازمة تنفسية انسدادية حادة'),
          ('Syndrome sec (hépatite à virus C)',376,11,'متلازمة جافة'),
          ('Syndrome vertigineux',377,2,'متلازمة دوار'),
          ('Syndromes myélodysplasiques acquis et non médicamenteux',378,7,'متلازمة خلل التنسج النقوي المكتسبة و غير الناجمة عن الأدوية'),
          ('Syndromes myéloprolifératifs',379,7,'متلازمة تكاثر خلايا النخاع العظمي'),
          ('Synovite (Mycobactérium bovis)',380,5,'التهاب زليلي'),
          ('Tableau pseudo-typhoïdique (brucellose aigue avec septicémie)',381,5,'حمى شبه تيفية'),
          ('Talcose',382,1,'سحار طالكي'),
          ('Tendinite achiliéenne',383,2,'التهاب العرقوب'),
          ('Tendinite de la patte d''oie',384,2,'التهاب أوتار رضفة الإوزة'),
          ('Tendinite du poignet - main et doigt',385,2,'التهاب أوتار المعصم ,اليد و الأصابع'),
          ('Tendinite sous-quadricipitale ou rotulienne',386,2,'التهاب أوتار تحت العضلة رباعية الرأس أو الأوتار الرضفية'),
          ('Tendinopathie aigue de l''épaule (non rompue non calcifiante avec ou sans enthésopathie de la coiffe des rotateurs)',387,2,'اعتلال حاد للأوتار غير منقطع و غير مكلس يكون مصحوبا أو غير مصحوب بالتهاب أماكن ارتباط غطاء العضلات المدورة'),
          ('Tendinopathie chronique de l''épaule (non rompue non calcifiante avec ou sans enthésopathie de la coiffe des rotateurs)',388,2,'اعتلال مزمن للأوتار غير منقطع و غير مكلس يكون مصحوبا أو غير مصحوب بالتهاب أماكن ارتباط غطاء العضلات المدورة'),
          ('Ténosynovite du poignet - main et doigt',389,2,'التهاب أغماد أوتار المعصم , اليد و الأصابع'),
          ('Tétanos',390,5,'الكزاز'),
          ('Thrombopénie (intoxication subaigue)',391,10,'نقص الصفائح الدموية'),
          ('Tremblement intentionnel',392,9,'ارتعاش قصدي'),
          ('Tremblements intentionnels',393,9,'ارتجاج قصدي'),
          ('Troubles angioneurotiques de la main prédominant à l''index et au médius, pouvant s''accompagner de crampes de la main et de troubles prolongés de la snesibilité et confirmés par des épreuves fonctionnelles et des examens radiologiques objectivant le phénomène de Raynaud',394,9,'اضطرابات وعائية عصبية باليد تظهر أكثر بالإبهام و الوسطة يمكن أن تصحبها تشنجات باليد و اضطرابات مطولة في القدرة علة التلمس و مثبتة بدلائل وظيفية و فحوص إشعاعية تظهر أعراض "راينود"'),
          ('Troubles angio-neurotiques des doigts et des orteils',395,9,'اضطرابات وعائية عصابية بأصابع اليد و القدم'),
          ('Troubles cardiaques aigus à type d''hyperexcitabilité ventriculaire ou supraventriculaire et disparaissant après l''arrêt de l''exposition au produit',396,8,'اضطرابات قلبية حادة علة شكل انفعالات مفرطة في البطين أة فوق البطين و التي تختفي بعد التوقف عن التعرض للمادة'),
          ('Troubles de la conduction (borréliose de Lyme)',397,9,'اضطرابات التوصيل'),
          ('Troubles de la sensibilité (borréliose de Lyme)',398,9,'اضطرابات التحسس'),
          ('Troubles de l''hémostase (intoxication aigue)',399,10,'اضطرابات خاصية الإرقاء'),
          ('Troubles digestifs immédiats',400,11,'الاضطرابات الهضمية المباشرة'),
          ('Troubles du rythme',401,10,'اضطرابات نبض القلب'),
          ('Troubles gastro-intestinaux aigus avec nausées, vomissements ou diarrhées',402,11,'اضطرابات حادة بالمعدة و الأمعاء مصحوبة بغثيان و قيئ و إسهال'),
          ('Troubles gastro-intestinaux apyrétiques accompagnés de vomissements à répétition',403,11,'اضطرابات معدية معوية غير حمية مصحوبة بفقيئ متكرر'),
          ('Troubles labyrinthiques',404,2,'اضطرابات المتاهة'),
          ('Troubles psychiques aigus avec confusion mentale, délire onirique',405,9,'اضطرابات نفسية حادة مع خلط ذهني و هذيان منامي'),
          ('Troubles psychiques chroniques avec états dépressifs et impulsions morbides',406,9,'اضطرابات نفسية مزمنة مع حالات اكتئاب و اندفاعات مرضية'),
          ('Troubles transitoires de la conduction cardiaque (intoxication aigue)',407,10,'اضطرابات عابرة في تدفق الدم'),
          ('Troubles transitoires de l''excitabilité cardiaque (intoxication aigue)',408,10,'اضطرابات عابرة في استثارة القلب'),
          ('Tuberculose cutanée ou sous-cutanée (Mycobactérium bovis)',409,5,'السل الجلدي أو تحت الجلدي'),
          ('Tuberculose extra-thoracique (Mycobactérium tuberculosis, Mycobactérium bovis, Mycobactérium africanum)',410,5,'اليل خارج القفص الصدري'),
          ('Tuberculose ganglionnaire (Mycobactérium bovis)',411,5,'السل العقدي'),
          ('Tuberculose ou autre mycobactériose (complication)',412,1,'السل أو غيره من أمراض المتفطرات المنضافة و المتبثة'),
          ('Tuberculose pleurale (Mycobactérium tuberculosis, Mycobactérium bovis, Mycobactérium africanum)',413,5,'سل ذات الجنب'),
          ('Tuberculose pulmonaire (Mycobactérium tuberculosis, Mycobactérium bovis, Mycobactérium africanum)',414,5,'السل الرئوي'),
          ('Tumeur primitive de l''épithélium urinaire (vessie, voies excrétrices supérieures)',415,3,'ورم بدائي بالظهارة البولية (المثانة و المسالك البولية العلوية)'),
          ('Tumeurs pleurales primitives',416,3,'أورام أخرى جنوبية بدائية'),
          ('Ulcérations',417,4,'تقرحات الجلد'),
          ('Ulcérations cutanées (effets caustiques)',418,4,'تقرح حاجز الأنف (التأثيرات الكاوية)'),
          ('Ulcérations cutanées chroniques ou récidivantes',419,4,'تقرحات الجلد المزمنة أو المتكررة'),
          ('Ulcérations Nasales',420,2,'تقرحات الأنف'),
          ('Urticaire (hépatite à virus B)',421,4,'شرى  (التهاب الكبد بفيروس B)'),
          ('Urticaire (hépatite à virus C)',422,4,'شرى (التهاب الكبد بفيروس C)'),
          ('Urticaire de contact ayant récidivé après nouvelle exposition',423,4,'طفح جلدي ملامس متكرر بعض التعرض من جديد للخطر و متبث باختبار'),
          ('Varicelle grave généralisée (complications de la varicelle)',424,5,'جدري مائي خطير معمم'),
          ('Vascularites (hépatite à virus B)',425,13,'التهاب الأوعية الدموية'),
          ('Vertiges',426,2,'دوار'),
          ('Vomissements (intoxication aigue)',427,10,'تقيؤ (التسمم الحاد)'),
          ('Zona et ses manifestations cutanées, auriculaire, ophtalmique, méningée, neurologique périphérique; algies post zostériennes (Complications dues à l''infection chronique par le virus de la varicelle)',428,5,'الحلأ النطاقي و مظاهره الجلدية, الأذنية , العينية, التهاب السحايا, و الجهاز العصبي الطرفي, آلام ما بعد الحلأ النطاقي للشخص الذي كان يعاني سابقا من جدري الماء')
          `);
        }
      });})

 // Vérification et insertion dans Agents
 db.transaction(tx => {  tx.executeSql('SELECT COUNT(*) AS count FROM Agents', [], (tx, results) => {
  console.log('DUDU');
  if (results.rows.item(0).count === 0) {
    tx.executeSql(`INSERT INTO Agents (LibelleFR,ID,NTAB,LibelleAR) VALUES
    ('Plomb et ses composés',1,'1.1.1','الرصاص و مركباته'),
    ('Fluor, Acide fluorhydrique et ses sels minéraux',2,'1.1.10','الفليور و حمض الفليوريدريك و أملاحه المعدنية'),
    ('Ciments (Alumino-silicates de calcium)',3,'1.1.11','الاسمنت (ألمنيو-سيلسكاتات الكلسيوم)'),
    ('Poussières minérales renfermant de la silice cristaline (quartz, cristobalite, tridymite), des silicates cristallins ( koalin, talc), du graphite ou de la houille',4,'1.1.12','الغبار المعدني المحتوي على السيليس البلوري (كوارتز, كريستوباليت, تريديميت), أو السيليكات البلورية (الصلصال, الطالك) أو الغرافيت أو الفحم الحجري'),
    ('Poussières d''amiante',5,'1.1.13','غبار الحرير الصخري'),
    ('Poussières d''amiante (cancer broncho-pulmonaire)',6,'1.1.13 bis','غبار الحرير الصخري (السرطان بالقصبات الهوائية)'),
    ('Cadmium et ses composés',7,'1.1.14','الكادميوم و مركباته'),
    ('Poussières ou fumées renfermant du cadmium (cancer broncho-pulmonaire)',8,'1.1.14 bis','غبار أو دخان يحتوي على الكادميوم (السرطان بالقصبات الهوائية)'),
    ('Mines de charbon (BPCO)',9,'1.1.15','منجمو الفحم (الالتهاب القصبي الرئوي الانسدادي)'),
    ('Charbon',10,'1.1.15','الفحم'),
    ('Mines de fer (BPCO)',11,'1.1.16','منجمو الحديد (الالتهاب القصبي الرئوي الانسدادي)'),
    ('Fer',12,'1.1.16','الحديد'),
    ('Poussières minérales ou de fumées, contenant des particules de fer ou d''oxyde de fer',13,'1.1.17','غبار معدني أو أدخنة تحتوي على جزيئات الحديد أو أكسيد الحديد'),
    ('Travaux aux fond dans les mines de fer',14,'1.1.17 bis','العمل في باطن مناجم الحديد'),
    ('Chlorure de sodium dans les mines de sel et leurs dépendances',15,'1.1.18','كلوريد الصوديوم داخل مناجم الملح و ملحقاتها'),
    ('Acide chromique, chromâtes et bichromates alcalins, chromate de zinc et le sulfate de chrome (ulcérations et dermites)',16,'1.1.19','حمض الكروم و الكروماتات و ثاني الكروماتات القلوية و كرومات الزنك و سولفات الكروم (التقرحات و الالتهابات الجلدية)'),
    ('Acide chromique, les chromates et bichromates alcalins (affections respiratoires)',17,'1.1.19 bis','حمض الكروم و الكروماتات و ثاني الكروماتات القلوية (الإصابات التنفسية)'),
    ('Acide chromique, chromates et bichromates alcalins (affections respiratoires)',18,'1.1.19 bis',' ﺣﻤﺾ ﺍﻟﻜﺮﻭﻡ ﺍﻟﻜﺮﻭﻣﺎﺗﺎﺕ ﻭﺛﺎﻧﻲ ﺍﻟﻜﺮﻭﻣﺎﺗﺎﺕ  ﺍﻟﻘﻠﻮﻳﺔ (الإصابات التنفسية)'),
    ('Acide chromique et les chromates et bichromates alcalins ou alcalino-terreux ainsi que le chromate de zinc (affections cancéreuses)',19,'1.1.19 ter','حمض الكروم و الكروماتات و ثاني الكروماتات القلوية أو القلوي الطيني و عن كرومات الزنك (الإصابات السرطانية)'),
    ('Mercure et ses composés',20,'1.1.2','الزئبق و مركباته'),
    ('Sélénium et ses dérivés minéraux',21,'1.1.20','السيلينيوم ﻭﻣﺸﺘﻘﺎﺗﻪ ﺍﻟﻤﻌﺪﻧﻴﺔ '),
    ('Antimoine et ses dérivés',22,'1.1.21','الأثمد (الكحل) و مشتقاته'),
    ('Manganèse',23,'1.1.3','المنغنيز'),
    ('Cobalt et ses composés',24,'1.1.4','الكوبالت و مركباته'),
    ('Poussières de carbures métalliques frittés ou fondus contenant du cobalt (Affections respiratoires)',25,'1.1.4 bis','غبار الكربيدات المعدنية الملبدة أو المنصهرة التي تحتوي على الكوبالت'),
    ('Poussières de cobalt associèes au carbure de tungstène avant frittage (Affections cancéreuses)',26,'1.1.4 ter','أغبرة الكوبالت المرتبطة بكربيد التنغستن قبل التلبيد'),
    ('Béryllium et ses composés',27,'1.1.5','البرليوم و مركباته'),
    ('Arsenic et ses composés minéraux',28,'1.1.6','الزرنيخ و مركباته المعدنية'),
    ('Poussières et vapeurs arsenicales (cancer bronchique primitif)',29,'1.1.6 bis','الغبار و الأبخرة الزرنيخية (السرطان البدائي بالقصبات الهوائية)'),
    ('Poussières et vapeurs renfermant des arseno-pyrites aurifères (cancer bronchique primitif)',30,'1.1.6 ter','غبار أو بخار يحتوي على زرنيخات البيريت المحتوية على الذهب '),
    ('Hydrogène arsénié',31,'1.1.7','الهيدروجين الزرنيخي'),
    ('Oxydes et sels de nickel (Affections cutanées)',32,'1.1.8','أكسيدات و أملاح النيكل (الإصابات الجلدية)'),
    ('Oxydes et sels de nickel (affections respiratoires)',33,'1.1.8 bis','أكسيدات و أملاح النيكل (الإصابات التنفسية)'),
    ('Grillage des mattes de nickel',34,'1.1.8 ter','ﻋﻤﻠﻴﺎﺕ ﺣﺮﻕ ﺍﻟﻨﻴﻜﻞ ﻏﻴﺮ ﺍﻟﻤﻜﺘﻤﻞ ﺍﻟﺘﺼﻨﻴﻊ'),
    ('Phosphore et sesquisulfure de phosphore',35,'1.1.9','الفوسفور و سادس سلفور الفسفور'),
    ('Hydrocarbures aliphatiques halogénés énumérés ci-après : dichlorométhane ; trichlorométhane ; tribromométhane ; triiodométhane ; tétrabromométhane ; chloroéthane ; 1,1-dichloroéthane ; 1,2-dichloroéthane ; 1,2-dibromoéthane ; 1,1,1- trichloroéthane ; 1,1,2-trichloroéthane ; 1,1,2,2-tétrabromoéthane ; pentachloroéthane ; 1-bromopropane ; 2-bromopropane ; 1,2- dichloropropane ; trichloroéthylène ; tétrachloroéthylène ; dichloro- acétylène ; trichlorofluorométhane ; 1,1,2,2-tétrachloro - 1,2-difluoroéthane ; 1,1,1,2-tétrachloro - 2,2-difluoroéthane ; 1,1,2-trichloro - 1,2,2- trifluoroéthane ; 1,1,1-trichloro - 2,2,2-trifluoroéthane ; 1,1-dichloro - 2,2,2- trifluoroéthane ; 1,2-dichloro - 1,1-difluoroéthane ; 1,1-dichloro - 1- fluoroéthane. ',36,'1.2.1','ﺍﻟﻬﺪﺭﻭﻛﺎﺭﺑﻮﻧﻴﺎﺕ ﺍﻷﻟﻴﻔﻴﺎﺗﻴﺔ ﺍﻟﻬﺎﻟﻮﺟﻴﻨﻴﺔ ﺍﻟﻤﺪﺭﺟﺔ ﺃﺩﻧﺎﻩ : ﺛﺎﻧﻲ ﻛﻠﻮﺭ ﺍﻟﻤﻴﺜﺎﻥ/ ﺛﻼﺛﻲ ﻛﻠﻮﺭ ﺍﻟﻤﻴﺜﺎﻥ/ ﺛﻼﺛﻲ ﺑﺮﻭﻣﻮ ﺍﻟﻤﻴﺜﺎﻥ/ ﺛﻼﺛﻲ ﺇﻳﻮﺩﻭ ﺍﻟﻤﻴﺜﺎﻥ/ ﺭﺑﺎﻋﻲ ﺑﺮﻭﻣﻮ ﺍﻟﻤﻴﺜﺎﻥ/ ﻛﻠﻮﺭﻭﺇﻳﺜﺎﻥ 1٬1/ ­ﺛﻨﺎﺋﻲ ﻛﻠﻮﺭﻭ ﻣﻴﺜﺎﻥ 1٬2 / ­ﺛﻨﺎﺋﻲ ﻛﻠﻮﺭﻭ ﺇﻳﺜﺎﻥ 1٬2 / ­ﺛﻨﺎﺋﻲ ﺑﺮﻭﻣﻮ ﻣﻴﺜﺎﻥ 1٬1٬1 / ﻛﻠﻮﺭﻭ ﺇﻳﺜﺎﻥ 1٬1٬2٬/ ﺛﻼﺛﻲ ﻛﻠﻮﺭﻭ ﺇﻳﺜﺎﻥ 2,2,1,1 ٬/ ﺭﺑﺎﻋﻲ ﺑﺮﻭﻣﻮ ﺇﻳﺘﺎﻥ/ ﺧﻤﺎﺳﻲ ﻛﻠﻮﺭﻭ ﺇﻳﺘﺎﻥ ٬1 / ﺑﺮﻭﻣﻮ ﺑﺮﻭﺑﺎﻥ ٬2 / ﺑﺮﻭﻣﻮ ﺑﺮﻭﺑﺎﻥ 2 ٬ 1 / ﺛﻨﺎﺋﻲ ﻛﻠﻮﺭﻭ ﺑﺮﻭﺑﺎﻥ / ﺛﻼﺛﻲ ﻛﻠﻮﺭ ﺇﺗﻴﻠﻴﻦ / ﺭﺑﺎﻋﻲ ﻛﻠﻮﺭ ﺇﺗﻴﻠﻴﻦ / ﺛﺎﻧﻲ ﻛﻠﻮﺭ ﺃﺳﻴﺘﻴﻠﻴﻦ/ ﺛﻼﺛﻲ ﻛﻠﻮﺭﻭ ﻓﻠﻴﻮﺭﻭﻣﻴﺘﺎﻥ 2 ٬ 2 ٬ 1 ٬ 1 / ­ﺭﺍﺑﻊ ﻛﻠﻮﺭﻭ 2 ٬1 ﺛﻨﺎﺋﻲ ﻓﻠﻴﻮﺭﻭﺇﻳﺘﺎﻥ 2 ٬ 1 ٬ 1 ٬ 1 / ﺭﺍﺑﻊ ﻛﻠﻮﺭﻭ 2٬2 ﺛﻨﺎﺋﻲ ﻓﻠﻴﻮﺭﻭﺇﻳﺘﺎﻥ 2 ٬ 1 ٬ 1 / ﺛﻼﺛﻲ ﻛﻠﻮﺭﻭ­ 1٬2٬2 ­ﺛﻼﺛﻲ ﻓﻠﻴﻮﺭﻭﺇﻳﺘﺎﻥ 1.1.1 / ﺛﻼﺛﻲ ﻛﻠﻮﺭﻭ­ 2 ٬ 2 ٬ 2 ﺛﻼﺛﻲ ﻓﻠﻴﻮﺭﻭﺇﻳﺘﺎﻥ 1 ٬ 1 / ﺛﻨﺎﺋﻲ ﻛﻠﻮﺭﻭ ­ 2٬2٬2 ﺛﻼﺛﻲ ﻓﻠﻴﻮﺭﻭﺇﻳﺘﺎﻥ 2 ٬ 1 / ­ﺛﻨﺎﺋﻲ ﻛﻠﻮﺭﻭ­ 1٬1 ­ﺛﻨﺎﺋﻲ ﻓﻠﻴﻮﺭﻭﺇﻳﺘﺎﻥ 1 ٬ 1 / ﺛﻨﺎﺋﻲ ﻛﻠﻮﺭﻭ ­ ­1 ﻓﻠﻴﻮﺭﻭﺇﻳﺘﺎﻥ '),
    ('Amines aromatiques, leurs sels et leurs dérivés notamment hydroxylés, halogénés, nitrés, nitrosés et sulfonés ',37,'1.2.10',' ﺍﻷﻣﻴﻨﺎﺕ ﺍﻟﻌﻄﺮﻳﺔ ﻭﺃﻣﻼﺣﻬﺎ ﻭﻣﺸﺘﻘﺎﺗﻬﺎ ﺧﺎﺻﺔ ﺍﻟﻬﻴﺪﺭﻭﻛﺴﻴﻠﻴﺔ ﻭﺍﻟﻬﺎﻟﻮﺟﻴﻨﻴﺔ ﻭﺍﻟﻨﻴﺘﺮﻳﺔ ﻭﺍﻟﻨﻴﺘﺮﻭﺯﻧﻴﺔ ﻭﺍﻟﺴﻠﻔﻮﻧﻴﺔ'),
    ('Amines aromatiques et leurs sels, leurs dérivés notamment hydroxylés, halogénés, nitrés, nitrosés et sulfonés et les produits qui en contiennent à l''état libre (affections de mécanisme allergique)',38,'1.2.10 bis','ﺍﻷﻣﻴﻨﺎﺕ ﺍﻟﻌﻄﺮﻳﺔ ٬ ﺃﻣﻼﺣﻬﺎ ﻭﻣﺸﺘﻘﺎﺗﻬﺎ ﺧﺎﺻﺔ ﺍﻟﻬﻴﺪﺭﻭﻛﺴﻴﻠﻴﺔ ﻭﺍﻟﻬﺎﻟﻮﺟﻴﻨﻴﺔ ﻭﺍﻟﻨﻴﺘﺮﻳﺔ ﻭﺍﻟﻨﻴﺘﺮﻭﺯﻳﺔ ﻭﺍﻟﺴﻠﻔﻮﻧﻴﺔ ﻭ ﻛﺬﺍ ﺍﻟﻤﻮﺍﺩ ﺍﻟﺘﻲ ﺗﺤﺘﻮﻳﻬﺎ ﻓﻲ ﺣﺎﻟﺘﻬﺎ ﺍﻟﻄﺒﻴﻌﻴﺔ (ﺇﺻﺎﺑﺎﺕ الحساسية)'),
    ('Amines aromatiques et leurs sels et la N-Nitroso-dibutylamine et ses sels  (lésions primitives de la vessie)',39,'1.2.10 ter','ﺍﻷﻣﻴﻨﺎﺕ ﺍﻟﻌﻄﺮﻳﺔ ﻭﺃﻣﻼﺣﻬﺎ ﻭ ﺛﺎﻧﻲ ﺑﻴﺘﻴﻼﻣﻴﻦ ﻧﺘﺮﻭﺯﻭ ﻭ ﺃﻣﻼﺣﻪ (إصابات بالمثانة ميالة إلى التكاثر)'),
    ('Amines aliphatiques, alicycliques ou les éthanolamines (affections cutanées)',40,'1.2.11','ﺍﻻﻣﻴﻨﺎﺕ ﺍﻻﻟﻴﻔﺎﺗﻴﺔ ﻭﺍﻻﻟﻴﺴﻴﻜﻠﻴﺔ ﻭ ﺃﻣﻴﻨﺎﺕ ﺍﻻﻳﺘﺎﻧﻮﻝ (الإصابات الجلدية)'),
    ('Amines aliphatiques, les éthanolamines ou l''isophoronediamine (affections respiratoires)',41,'1.2.11 bis',' ﺍﻻﻣﻴﻨﺎﺕ ﺍﻻﻟﻴﻔﺎﺗﻴﺔ ﻭ ﺃﻣﻴﻨﺎﺕ ﺍﻻﻳﺘﺎﻧﻮﻝ ﺃ ﻭ ﺇﻳﺰﻭﻓﻮﺭﻭﻧﻴﺪﻳﺎﻣﻴﻦ (الإصابات التنفسية)'),
    ('Hexane ',42,'1.2.12','الإكزان'),
    ('Tétrachloréthane',43,'1.2.13','ﺭﺍﺑﻊ ﻛﻠﻮﺭﻳﺪ ﺍﻻﻳﺘﺎﻥ'),
    ('Tétrachlorure de carbone',44,'1.2.14','ﺭﺍﺑﻊ ﻛﻠﻮﺭﻳﺪ ﺍﻟﻜﺮﺑﻮﻥ'),
    ('Bromure de méthyle',45,'1.2.15','ﺑﺮﻭﻣﻮﺭ ﺍﻟﻤﻴﺘﻴﻞ'),
    ('Chlorure de méthyle ',46,'1.2.16','ﻛﻠﻮﺭﻳﺪ ﺍﻟﻤﻴﺘﻴﻞ'),
    ('Méthacrylate de méthyle ',47,'1.2.17',' ﻣﻴﺘﺎﻛﺮﻳﻼﺕ ﺍﻟﻤﻴﺘﻴﻞ'),
    ('Bis (Chlorométhyle) éther (affections malignes)',48,'1.2.18','ﺛﺎﻧﻲ (ﻛﻠﻮﺭﻭﻣﻴﺘﻴﻞ ) إثير (الإصابات الخبيثة)'),
    ('Furfural et l''alcool furfurylique ',49,'1.2.19','ﺍﻟﻔﻮﺭﻓﻮﺭﺍﻝ ﻭﺍﻟﻜﺤﻮﻝ ﺍﻟﻔﻮﺭﻓﻮﺭﻳﻠﻲ'),
    ('Benzène et tous les produits en renfermant (Hémopathies)',50,'1.2.2','ﺍﻟﺒﻨﺰﻳﻦ ﻭﺟﻤﻴﻊ ﺍﻟﻤﻮﺍﺩ ﺍﻟﺘﻲ ﺗﺤﺘﻮﻱ ﻋﻠﻴﻪ (ﺃﻣﺮﺍﺽ ﺍﻟﺪﻡ)'),
    ('Benzène , toluène, xylènes et tous les produits les renfermant (affections gastro-intestinales)',51,'1.2.2 bis','ﺍﻟﺒﻨﺰﻳﻦ ﻭﺍﻟﻄﻠﻮﻧﻴﻦ ﻭﺍﻟﺰﻳﻠﻴﻨﺎﺕ ﻭﺟﻤﻴﻊ ﺍﻟﻤﻮﺍﺩ ﺍﻟﺘﻲ ﺗﺤﺘﻮﻱ ﻋﻠﻴﻬﺎ (الإصابات المعدية و المعوية) '),
    ('Solvants organiques liquides à usage professionnel : hydrocarbures liquides aliphatiques, alicycliques, hétérocycliques et aromatiques et leurs mélanges (white spirit, essences spéciales); dérivés nitrés des hydrocarbures alipahtiques; acétonitrile; alcools, aldéhydes, cétones, esters, éthers dont le tétrahydrofurane, glycols et leurs éthers; diméthylformamide; diméthylsulfoxyde',52,'1.2.20','ﺍﻟﻤﺬﻳﺒﺎﺕ ﺍﻟﻌﻀﻮﻳﺔ ﺍﻟﺴﺎﺋﻠﺔ ﺫﺍﺕ ﺍﻻﺳﺘﻌﻤﺎﻝ ﺍﻟﻤﻬﻨﻲ ﺍﻟﻬﻴﺪﺭﻭﻛﺎﺭﺑﻮﻧﻴﺎﺕ ﺍﻟﺴﺎﺋﻠﺔ ﺍﻷﻟﻴﻔﺎﺗﻴﺔ ﻭﺍﻷﻟﻴﺴﻜﻠﻴﺔ ﻭﺍﻻﻳﺘﻴﺮﻭﺳﻜﻠﻴﺔ ﻭﺍﻟﻌﻄﺮﻳﺔ ﻭﺃﺧﻼﻃﻬﺎ (ﻭﺍﻳﺖ ﺳﺒﻴﺮﻳﺖ ﺍﻟﺒﻨﺰﻳﻨﺎﺕ ﺍﻟﺨﺎﺻﺔ) ﻭﺍﻟﻤﺸﺘﻘﺎﺕ ﺍﻟﻨﺘﺮﻳﺔ ﻣﻦ ﺍﻟﻬﻴﺪﺭﻭﻛﺎﺭﺑﻮﻧﻴﺎﺕ ﺍﻷﻟﻴﻔﺎﺗﻴﺔ ﻭﺍﻻﺳﻴﺘﻮﻧﺘﺮﻳﻞ ﻭﺍﻟﻜﺤﻮﻝ ﻭﺍﻹﻟﺪﻳﻬﻴﺪﺍﺕ ﻭﺍﻟﺴﻴﺘﻮﻧﺎﺕ ﻭﺍﻻﺳﺘﻴﺮﺍﺕ ﻭ ﺍﻹﻳﺘﻴﺮﺍﺕ ﺑﻤﺎ ﻓﻴﻬﺎ ﺭﺍﺑﻊ ﺍﻟﻬﻴﺪﺭﻭﻓﻮﺭﺍﻥ ﻭﺍﻟﻐﻠﻴﻜﻮﻻﺕ ﻭﺇﺛﻴﺮﺍﺗﻬﺎ ﻭﺛﺎﻧﻲ ﻣﻴﺘﻴﻞ ﺍﻟﻔﻮﺭﻣﺎﻣﻴﺪ ﻭﺛﺎﻧﻲ ﻣﻴﺘﻴﻞ ﺍﻟﺴﻠﻔﻮﻛﺴﻴﺪ'),
    ('Phénylhyarazine ',53,'1.2.21',' ﺍﻟﻔﻴﻨﻴﻠﻬﻴﺪﺭﺍﺯﻳﻦ'),
    ('Goudrons de houille, les huiles de houille (comprenant les fractions de distillations dites phénoliques, naphtaléniques, acénaphténiques, anthracéniques et chryséniques), les brais (affections cutanées)',54,'1.2.22','ﻗﻄﺮﺍﻥ ﺍﻟﻔﺤﻢ ﺍﻟﺤﺠﺮﻱ ﻭﺯﻳﻮﺗﻪ (ﺍﻟﻤﺤﺘﻮﻳﺔ ﻋﻠﻰ ﺃﺟﺰﺍء ﺗﻘﻄﻴﺮ ﺗﺴﻤﻰ :ﻓﻴﻨﻮﻟﻴﺔ ﻭﻧﻔﺘﺎﻟﻴﻨﻴﺔ ﻭﺍﺳﻴﻨﻔﺘﻴﻨﻴﺔ ﻭﺍﻧﺘﺮﺍﺳﻴﻨﻴﺔ ﻭﻛﺮﻳﺴﻴﻨﻴﺔ) ﺯﻓﺖ ﺍﻟﻔﺤﻢ ﺍﻟﺤﺠﺮﻱ'),
    ('Goudrons de houille, les huiles de houille, les brais de houille et les suies de combustion du charbon (affections cancéreuses)',55,'1.2.22 bis','ﻗﻄﺮﺍﻥ ﺍﻟﻔﺤﻢ ﺍﻟﺤﺠﺮﻱ ﻭﺯﻳﻮﺗﻪ ﻭ ﺯﻓﺖ ﺍﻟﻔﺤﻢ ﺍﻟﺤﺠﺮﻱ ﻭﺍﺳﻨﺠﺔ ﺍﻟﻔﺤﻢ ﺍﻟﻤﺤﺮﻭﻕ (الإصابات الجلدية)'),
    ('Sulfocarbonisme ',56,'1.2.23','ﺳﻠﻔﻮﺭ ﺍﻟﻜﺮﺑﻮﻥ ﺍﻟﻤﻬﻨﻲ'),
    ('Dérivés halogénés des hydrocarbures aromatiques (monochlorobenzène, monobromobenézne, hexachlorobenzène)',57,'1.2.3',' ﺍﻟﻤﺸﺘﻘﺎﺕ ﺍﻟﻬﺎﻟﻮﺟﻴﻨﻴﺔ ﻟﻠﻬﺪﺭﻭﻛﺎﺭﺑﻴﺪﺍﺕ ﺍﻟﻌﻄﺮﻳﺔ'),
    ('Dérivés nitrées et chloronitrées des hydrocarbures benzéniques',58,'1.2.4','ﺍﻟﻤﺸﺘﻘﺎﺕ ﺍﻟﻨﺘﺮﻳﺔ ﻭ ﺍﻟﻜﻠﻮﺭﻭﻧﺘﺮﻳﺔ ﻟﻠﻜﺮﺑﻴﺪﺍﺕ ﺍﻟﺒﻨﺰﻳﻨﻴﺔ '),
    ('Huiles et graisses d''origine minérale ou de synthèse ',59,'1.2.5',' ﺍﻟﺰﻳﻮﺕ ﻭ ﺍﻟﺸﺤﻮﻡ ﺍﻟﻤﻌﺪﻧﻴﺔ ﺍﻟﻤﺼﺪﺭ ﺃﻭ ﺍﻟﻤﻨﺸﺄﺓ ﻛﻴﻤﺎﻭﻳﺎ. '),
    ('Dérivés du pétrole : Huiles minérales peu ou non raffinées, huilles minérales régénérées utilisées dans les opérations d''usinage et de traitement des métaux, extraits aromatiques, résidus de craquage, huiles moteur usagées, suies de combustion des produits pétroliers ',60,'1.2.5 bis','ﻣﺸﺘﻘﺎﺕ ﺍﻟﺒﺘﺮﻭﻝ ﺍﻟﺘﺎﻟﻴﺔ : ﺍﻟﺰﻳﻮﺕ ﺍﻟﻤﻌﺪﻧﻴﺔ ﺍﻟﻘﻠﻴﻠﺔ ﺍﻟﺘﻜﺮﻳﺮ ﺃﻭ ﺍﻟﻐﻴﺮ ﻣﻜﺮﺭﺓ ﻭ ﺍﻟﺰﻳﻮﺕ ﺍﻟﻤﻌﺪﻧﻴﺔ ﺍﻟﻤﺠﺪﺩﺓ ﺍﻟﻤﺴﺘﻌﻤﻠﺔ ﻓﻲ ﺍﻟﻌﻤﻠﻴﺎﺕ ﺍﻟﻤﻌﻤﻠﻴﺔ ﻭﻓﻲ ﻣﻌﺎﻟﺠﺔ ﺍﻟﻔﻠﺰﺍﺕ ٬ ﺍﻟﻤﺴﺘﺨﺮﺟﺎﺕ ﺍﻟﻌﻄﺮﻳﺔ ٬ ﻣﺨﻠﻔﺎﺕ ﺍﻟﺘﻜﺴﻴﺮ ٬ ﺯﻳﻮﺕ ﺍﻟﻤﺤﺮﻙ ﺍﻟﻤﺴﺘﻌﻤﻠﺔ ﻭ ﺃﺳﻨﺠﺔ ﺣﺮﻕ ﺍﻟﻤﻮﺍﺩ ﺍﻟﻨﻔﻄﻴﺔ. '),
    ('Dérivés nitrés du phénol (dinitrophénols,dinitro-orthocrésol, dinoseb), par le pentachlorophénol, les pentachlorophénates et par les dérivés halogènes de l''hydroxybenzonitrile (bromoxynil, ioxynil) ',61,'1.2.6',' ﺍﻟﻤﺸﺘﻘﺎﺕ ﺍﻟﻨﺘﺮﻳﺔ ﻟﻠﻔﻴﻨﻮﻝ (ﺛﺎﻧﻲ ﻧﺘﺮ ﺍﻟﻔﻴﻨﻮﻻﺕ ﻭﺛﺎﻧﻲ ﻧﺘﺮ ﺍﻟﻜﺮﻳﺴﻮﻝ ﺍﻟﺴﻮﻱ و دينوساب) ﻭﺧﺎﻣﺲ ﻛﻠﻮﺭ ﺍﻟﻔﻴﻨﻮﻝ ﻭﺧﺎﻣﺲ ﻛﻠﻮﺭ ﺍﻟﻔﻴﻨﺎﺗﺎﺕ ﻭﺍﻟﻤﺸﺘﻘﺎﺕ ﺍﻟﻬﺎﻟﻮﺟﻴﻨﻴﺔ للهيدروكسيبنزونيتريل (ﺑﺮﻭﻣﻮﻛﺴﻴﻨﻴﻞ ﻭايوكسينيل)'),
    ('Dérivés nitrés des glycols et du glycérol ',62,'1.2.7','المشتقات ﺍﻟﻨﺘﺮﻳﺔ ﻣﻦ ﺍﻟﻐﻠﻴﻜﻮﻝ ﻭ ﺍﻟﻐﻠﻴﺴﺮﻭﻝ'),
    ('Aldéhyde formique et ses polymères ',63,'1.2.8',' ﺍﻟﻔﻮﺭﻣﺎﻟﺪﻳﻴﺪ ﻭﻣﻜﺎﺛﻴﺮﻩ'),
    ('Aldéhyde formique (Affections cancéreuses)',64,'1.2.8 bis','الفورمالدييد (الإصابات السرطانية)'),
    ('Aldéhyde formique',65,'1.2.8 bis',' ﺍﻟﻔﻮﺭﻣﺎﻟﺪﻳﻴﺪ '),
    ('Tricresylphosphate ',66,'1.2.9','ﺍﻟﺘﺮﻛﺮﺳﻴﻞ ﻓﻮﺳﻔﺎﻁ'),
    ('Résines époxydiques et leurs constituants ',67,'1.3.1','ﺍﻟﺮﺍﺗﻨﺠﺎﺕ ﺍﻻﺑﻮﻛﺴﻴﺪﻳﺔ ﻭ ﻣﻜﻮﻧﺎﺗﻬﺎ '),
    ('Isocyanates organiques ',68,'1.3.2','ﺍﻻﻳﺰﻭﺳﻴﺎﻧﺎﺗﺎﺕ ﺍﻟﻌﻀﻮﻳﺔ '),
    ('Opérations de polymérisation du chlorure de vinyle (durée d''exposition: 6 mois)',69,'1.3.3',' ﻋﻤﻠﻴﺎﺕ ﺑﻠﻤﺮﺓ ﻛﻠﻮﺭﻳﺪ ﺍﻟﻔﻴﻨﻴﻞ'),
    ('Pesticides ( Maladie de Parkinson)',70,'1.4.1','المبيدات (مرض الباركنسون)'),
    ('Phosphates, les pyrophosphates et thiophosphates d''alcoyle, d''aryle ou d''alcoylaryle et autres organophosphorés anticholinéstérasiques ainsi que par les phosphoramides et car bamates hétérocycliques anticholinéstérasiques ',71,'1.4.2',' ﺍﻟﻔﻮﺳﻔﺎﻁ ﻭﺍﻟﺒﻴﺮﻭﻓﻮﺳﻔﺎﻁ ﻭﺗﻴﻮﻓﻮﺳﻔﺎﻁ ﻟﻸﻟﻜﻮﻳﻞ ﻭﺍﻷﺭﻳﻞ ﻭﺍﻷﻟﻜﻮﻳﻼﺭﻳﻞ ﻭﻏﻴﺮﻫﺎ ﻣﻦ ﺍﻟﻔﻮﺳﻔﻮﺭﺍﺕ ﺍﻟﻌﻀﻮﻳﺔ ﺍﻟﻤﻀﺎﺩﺓ ﻷﻧﺰﻳﻢ ﺍﻟﻜﻮﻟﻴﻨﻴﺴﺘﻴﺮﺍﺱ ﻭﻛﺬﻟﻚ ﺍﻟﻔﻮﺳﻔﻮﺭﺍﻣﻴﺪﺍﺕ ﻭﺍﻟﻜﺮﺑﺎﻣﺎﺗﺎﺕ ﻣﺘﻐﺎﻳﺮﺓ ﺍﻟﺤﻠﻘﺎﺕ ﻭﺍﻟﻤﻀﺎﺩﺓ للكولينيستيراس'),
    ('Aminoglycosides, notamment la streptomycine, par la néomycine et ses sels ',72,'1.5.1','ﺍﻻﻣﻴﻨﺎﺕ ﺍﻟﻐﻠﻴﻜﻮﺳﻴﺔ ﺧﺎﺻﺔ ﺍﻟﺴﺘﺮﻳﺒﺘﻮﻣﻴﺴﻴﻦ ﻭ ﺍﻟﻨﻴﻮﻣﻴﺴﻴﻦ ﺃﻣﻼﺣﻬﺎ'),
    ('Bétalactamines (Pénicillines et leurs sels ) et les céphalosporines',73,'1.5.2','ﺍﻷﻣﺮﺍﺽ ﺍﻻﻛﺘﺎﻣﺎﺕ ﺧﺎﺻﺔ ﺍﻟﺒﻨﺴﻴﻠﻴﻦ ﻭ ﺃﻣﻼﺣﻬﺎ ﻭ ﺍﻟﺴﻴﻔﺎﻟﻮﺳﺒﻮﺭﻳﻨﺎﺕ'),
    ('Chlorpromazine (Largactyl)',74,'1.5.3','الكلوربرومازين'),
    ('Enzymes ',75,'1.5.4','الأنزيمات'),
    ('Halothane ',76,'1.5.5',' ﺍﻟﻬﺎﻟﻮﺗﺎﻥ'),
    ('Inhalation de poussières textiles végétales (affections respiratoires)',77,'1.6.1','ﻏﺒﺎﺭ ﺍﻷﻧﺴﺠﺔ ﺍﻟﻨﺒﺎﺗﻴﺔ (الإصابات التنفسية)'),
    ('Poussières de bois ',78,'1.6.2','ﻏﺒﺎﺭ ﺍﻟﺨﺸﺐ'),
    ('Protéines du latex (ou caoutchouc naturel) (affections professionnelles de mécanisme allergique)',79,'1.6.3','ﺑﺮﻭﺗﻴﻨﺎﺕ ﻟﺒﻦ ﺍﻟﻨﺒﺎﺕ (ﺃﻭ ﺍﻟﻤﻄﺎﻁ ﺍﻟﻄﺒﻴﻌﻲ) (الإصابات المهنية إوالية الحساسية)'),
    ('Oxyde de carbone ',80,'1.7','ﺃﻛﺴﻴﺪ ﺍﻟﻜﺮﺑﻮﻥ'),
    ('Animaux (y compris arthropodes et larves)',81,'1.8.1','الماشية و الحيوانات بما في ذلك مفصليات الأرجل و يرقاتها'),
    ('Azodicarbonamide notamment dans l''industrie des plastiques, du caouatchouc et au styrène, isophoronadiamine, aziridinepolyfonctionnelle, triglycidyl isocyanurate',82,'1.8.1','أزوديكاربوناميد خاصة في صناعة البلاستيك و المطاط , الستيرين و الإيزوفروناديمين و الأزردين المتعدد الوظائف و ثلاثي غليسيديل إيزوسيانورات'),
    ('Café vert',83,'1.8.1','البن الأخضر'),
    ('Carmin et poudres d''insectes',84,'1.8.1','الصبغ القرمزي'),
    ('Chloroplatinates pentoxyde de vanadium notamment dans la fabrication de catalyseurs',85,'1.8.1','كلورور بلاتينات خامس أكسيد الفاناديوم خاصة في صناعة المحفزات'),
    ('Colophane chauffée notamment de la soudure éléctronique',86,'1.8.1','صمغ البطم الساخن خاصة خلال عملية اللحام الالكتروني'),
    ('Colorants réactifs, notamment hétérocycles halogénés, acryloylamines ou vinyl-sulfones, pipéridinyl triazine, ninhydrine',87,'1.8.1','أصباغ كاشفة خاصة متعددة دورات الهالوجينات و الاكريلولامينات أو السولفون الفينيليو البيبيردينل و النينهيدرين'),
    ('Duvets',88,'1.8.1','الزغب'),
    ('Emanations de produits de pyrolyse du chlorure de polyvinyle ( notamment dans la soudure thermique), fréons, polyéthylène, polypropylène',89,'1.8.1','انبعاثات مواد التحليل الحراري (البيروليز) لكلورور البوليفنيل (خاصة في اللحام الحراري) ز الفريونات و نتعدد البروبيلين'),
    ('Farines',90,'1.8.1','الطحين'),
    ('Feutres naturels',91,'1.8.1','اللبد الطبيعية'),
    ('Filature et tissage de textiles d''origine végétale',92,'1.8.1','النسيج ﺫو الأصل النباتي'),
    ('Fongicides notamment les phtalimide et tétrachlorophtalonitrile',93,'1.8.1','مبيدات الفطريات خاصة الفتاليميد و رباعي كلورورفتالونتريل'),
    ('Fourrures',94,'1.8.1','الفراء'),
    ('Gommes végétales pulvérisées (arabique, adragante, psyllium, karaya notamment)',95,'1.8.1','الصمغ النباتي المسحوق خاصة الصمغ العربي, صمغ الكثراء, عشبة البراغيث و الكرايا'),
    ('Broyage des grains de céréales alimentaires, ensachage, utilisations de farines',96,'1.8.1','سحق الحبوب الغذائية, تكيس و استعمال الطحين'),
    ('Gypsophile (gypsophila paniculata)',97,'1.8.1','الجبسيات ( جبسو فيليا بنيكيلاتا)'),
    ('Henné',98,'1.8.1','الحناء'),
    ('Ipéca',99,'1.8.1','عرق الذهب'),
    ('Ouvertures des balles, cardage, peignage, filature et tissage de textiles d''origine végétale (notamment coton, sisal, kapok, chanvre, lin)',100,'1.8.1','فتح الحزمات, حلاجة و تمشيط و غزل و خياطة النسيج ذو الأصل النباتي (خاصة القطن, باهرة ليفية, القابون, القنب و الكتان)'),
    ('Oxyde d''éthylène, notamment lors de la stérilisation',101,'1.8.1','أوكسيد الايتيلان خاصة أثناء التعقيم'),
    ('Plumes',102,'1.8.1','الريش'),
    ('Pollens notamment de lycopodes',103,'1.8.1','اللقاحات خاصة الخدرية'),
    ('Poudre d''insecte',104,'1.8.1','مساحيق الحشرات'),
    ('Poussières végétales notamment asparagés, légumineuses, papillionacés, ombellifères, labiées, solanacées, pyrèthres',105,'1.8.1','الأغبرة النباتية خاصة الهليونية و القطانيات و الفراشيات و الخيميات و الشفويات و الباذنجانيات و الغرديب'),
    ('Protéine en aérosol',106,'1.8.1','البروتينات على شكل رذاذ '),
    ('Quinine',107,'1.8.1','الكينين'),
    ('Résidus d''extraction d''huiles, notamment de ricin et d''ambrette',108,'1.8.1','فضلات استخراج الزيوت خاصة زيت الخروع و حب المسك'),
    ('Séricine',109,'1.8.1','القز'),
    ('Soja',110,'1.8.1','الصوجا'),
    ('Spores notamment de lycopodes',111,'1.8.1','اللقاحات خاصة الخدرية'),
    ('Sulfites, bisulfites ou persulfates alcalins',112,'1.8.1','السولفيتات و ثنائي سولفيتات أو سولفيتات قلوية'),
    ('Tabac',113,'1.8.1','التبغ'),
    ('Travaux de désinfection et de stérilisation exposants à des émanations de: chlorhexidine, hexachlorophène, benzisothiazoline-3-one et ses dérivés, organomercuriels, ammoniums quaternaires et leurs dérivés, notamment le benzalkonium et le chlorure de lauryl diméthylbenzylammonium',114,'1.8.1','أعمال التطهير و التعقيم المعرضة لانبعاثات: الكلورهيكسيدين, سادس الكلوروفين, بنزيزوتيازولين 3 _أون و مشتقاته, خاصة البنزالكونيوم و كلوريد لوريل ثنائي ميثيل بنزيل أمونيوم'),
    ('Détergents, notamment l''isononanoyl oxybenzène sulfonate de sodium',115,'1.8.1','المنظفات خاصة إيزونانونيل أكسي بنزين سلفونات الصوديوم'),
    ('Chloramine T',116,'1.8.1','الكلورامين T'),
    ('Tétrazène',117,'1.8.1','تيترازن'),
    ('Polypeptides exposant notamment au dicyclohexyl carbodiimide, 4 méthyl-morpholine, dichlorobenzène sulfonate',118,'1.8.1','البروتين المتعدد المعرض خاصة لثنائي سيكلو هيكسيلكاربو ثاني الأميد 4 ميثيل المورفولين ثنائي كلورزبنزين سلفونات'),
    ('Travaux de reprographie exposant notamment aux sels de diazonium ou à l''hydroquinone',119,'1.8.1','النساخة التصويرية المعرضة خاصو لأملاح ثاني الأزونيوم أو للهيدروكينون'),
    ('Dérivés aminés des produits chlorés tel que la chloramine dans les piscines',120,'1.8.1','المشتقات الأمينية للمواد المحتويو على الكلور مثل الكلورامين في المسابح'),
    ('Spores de moisissures ou des actinomyocètes contaminant les particules végétales ou animales suivantes: bagasse de la canne à sucre, malt, paprika, liège, charcutrie, fromages (affinage), pâte à papier et poussières de bois (Pneumopathies d''hypersensibilité)',121,'1.8.1 bis','غبيرات العفن أو الفشريات الشعاعية المتشبعة) و المعدية للجزيئات النباتية أو الحيوانية التالية : تفل قصب السكر و الشعير و الفلفل الحلو و الفلين و الفلين و لحوم الخنازير , و الأجبان ( في عملية الإنضاج) و عجين الورق و غبار الخشب'),
    ('Inhalation de particules microbiennes ou mycéliennes dans les laboratoires de microbiologie et les locaux à caractère industriel, de bureaux ou d''habitation dont l''atmosphère est climatisée ou humidifiée par dispositif central (Pneumopathies d''hypersensibilité)',122,'1.8.1 bis','استنشاق الجزيئات الجرثومية أو الفطرية فب مختبرات علم الأحياء المجهري أو في المحلات ذات الطابع الصناعي حيث يكون الجو مكيفا أو مرطبا بواسطة جهاز مركزي '),
    ('Milieux contaminés par des micro-organismes aéroportés (bactéries, moisissures, algues); saunas, piscines, égouts, filières de traitemant des déchets (compostage et fabrication de composte), ateliers pollués par des aérosols d''huile de coupe contaminée (Pneumopathies d''hypersensibilité)',123,'1.8.1 bis','أوساط ملوثة بالكائنات الحية الدقيقة المحمولة جوا (البكتيريا و الفطريات و الطحالب) , الساونا و المسابح و قنوات مياه الصرف الصحي, و سلاكات معالجة النفايات (التسميد و صناعة السماد), وأوراش العمل الملوثة برذيذات زيت القطع الملوث'),
    ('Inhalation d''aérosols d''enzymes lors de la fabrication, la manipulation et l''utilisation de détergents et lessives (Pneumopathies d''hypersensibilité)',124,'1.8.1 bis','استنشاق رذيذات الإنزيمات عند صناعة و مناولة و استعمال المنظفات و مساحيق الغسيل'),
    ('Poussières végétales: Les opérations de préparation dans les filatures du coton: ouverture des balles, cardage, peignage (Pneumopathies d''hypersensibilité)',125,'1.8.1 bis','أغبرة النباتات: العمليات التحضيرية في غزل القطن: فتح الحزمات, الحلاجة و التمشيط'),
    ('Poussières végétales: le broyage des grains de céréales, l''ensachage et l''utilisation des farines (Pneumopathies d''hypersensibilité)',126,'1.8.1 bis','أغبرة النباتات: طحن الحبوب, التكييس و استعمال الدقيق'),
    ('Poussières végétales: la préparation et la manipulation des champignons comestibles (Pneumopathies d''hypersensibilité) ',127,'1.8.1 bis','أغبرة النباتات: إعداد و مناولة البن الأخضر و الشاي و فول الصوجا و التبغ و الجنجل و الشعير'),
    ('Poussières végétales: la fabrication et l''utilisation de la pâte à papier (Pneumopathies d''hypersensibilité)',128,'1.8.1 bis','أغبرة النباتات: تصنيع و استعمال عجينة الورق'),
    ('Poussières végétales: la manipulation et l''utilisation des algues et alginates (Pneumopathies d''hypersensibilité)',129,'1.8.1 bis','أغبرة النباتات: مناولة و استعمال الطحالب و الألجينات'),
    ('Inhalation d''aérosols de protéines animales : la manipulation et utilisation de poussières d''origine aviaire (Pneumopathies d''hypersensibilité)',130,'1.8.1 bis','استنشاق رذيذات البروتينات الحيوانية: مناولة و استعمال أغبرة مصدرها طيري'),
    ('Inhalation d''aérosols de protéines animales : l''élevage et la manipulation d''animaux, y compris les mammifères de laboratoire, les arthropodes et les produits marins ou d''origine marine (Pneumopathies d''hypersensibilité)',131,'1.8.1 bis','استنشاق رذيذات البروتينات الحيوانية: تربية و مناولة الحيوانات, بما فيها ثدييات المختبر و المفصليات و المنتجات البحرية أو من أصل بحري'),
    ('Inhalation d''aérosols de protéines animales : la manipulation de fourrures (Pneumopathies d''hypersensibilité)',132,'1.8.1 bis','استنشاق رذيذات البروتينات الحيوانية: مناولة الفراء'),
    ('Inhalation d''aérosols de protéines animales : la préparation du carmin cochenille (Pneumopathies d''hypersensibilité)',133,'1.8.1 bis','استنشاق رذيذات البروتينات الحيوانية: إعداد الصبغ القرمزي لحشرة المغافير'),
    ('Inhalation des polluants chimiques suivants lors de leur fabrication et mise en œuvre: - anhydrides d''acides volatils suivants : anhydrides phtaliques, trimellitiques, tétrachlorophtaliques, hexahydrophtaliques, himiques (Pneumopathies d''hypersensibilité)',134,'1.8.1 bis','استنشاق الملوثات الكيميائية أثناء تصنيعها و استعمالها: أنهدريدات الأحماض المتبخرة التالية: الانهدريدات الفتالية و ثالث المليتية و رابع الكلورو فتالية و سادس الهيدروفتالية و الهيمية'),
    ('Pneumopathies d''hypersensibilité ',135,'1.8.2',' أمراض إﻛﺰﻳﻤﻴﺔ ﺇﻭﺍﻟﻴﺔ ﺍﻟﺤﺴﺎﺳﻴﺔ'),
    ('Acide chloroplatinique',136,'1.8.2','الحامض الكلوروبلاتيني'),
    ('Chloroplatinales alcalins',137,'1.8.2','الكلوروبلاتينات القلوية'),
    ('Cobalt et ses dérivés',138,'1.8.2','الكوبالت و مشتقاته'),
    ('Persulfates alcalins',139,'1.8.2','البرسولفاتات القلوية'),
    ('Thioglycolate d''ammonium',140,'1.8.2','تيوغليكولات الامونيوم'),
    ('Epichlorhydrine',141,'1.8.2','الايبيكلوريدين'),
    ('Hypochlorites alcalins',142,'1.8.2','الايبوكلوريتات القلوية'),
    ('Ammoniums quaternaires et leurs sels, notamment dans les agents détergents cationiques',143,'1.8.2','الامونيومات الرباعية و أملاحها خاصة في المواد المنظفة الكاتونية'),
    ('Dodécyl-aminoéthyl glycine',144,'1.8.2','دودسيل_أمينو اتيل الغليسين'),
    ('Insecticides organochlorés',145,'1.8.2','مبيدات الحشرات الكلورية العضوية'),
    ('Phénothiazines',146,'1.8.2','الفينوتيازين'),
    ('Pipérazine',147,'1.8.2','البيبيرازين'),
    ('Mercapto-benzothiazole',148,'1.8.2','ميركابتو_بنزوتيازول'),
    ('Sulfure de tétraméthyl-thiurame',149,'1.8.2','سلفور رباعي المتيل تيورام'),
    ('Acide mercapto-propionique et ses dérivés ',150,'1.8.2','الحمض الماركابتوبروبيوني و مشتقاته'),
    ('N-isopropyl N-phenylpara-Phénylènediamine et ses dérivés',151,'1.8.2','ن_ايزوبروبيل ن_فينيل بارا فينيلين _ثاني الأمين و مشتقاته'),
    ('Hydroquinone et ses dérivés',152,'1.8.2','الهيدروكينون و مشتقاته'),
    ('Dithiocarbamates',153,'1.8.2','ثاني تيو الكربماتات'),
    ('Sels de diazonium, notamment chlorure de diéthylaminobenzènc diazonium',154,'1.8.2','أملاح ثاني الازونيوم خاصة كلوريدثاني الاتيل امينو بنزين ثاني الازونيوم'),
    ('Benzisothiazoline-3-one',155,'1.8.2','بنزيزوتيازولين 3_أون'),
    ('Dérivés de la thiourée',156,'1.8.2','مشتقات التيو يوريا'),
    ('Acrylates et méthacrylates',157,'1.8.2','الاكريلات و الميتاكريلات'),
    ('Résines dérivées du para-tert butylphénol et du para-tert-butylcatéchol',158,'1.8.2','الراتنجات المشتقة من بارا_تارت_بوتيلكاتيكول'),
    ('Dicyclohexylcarbodilmide',159,'1.8.2','ثاني سيكلو هيكسيلكاربو ثاني الاميد'),
    ('Glutaraldéhyde',160,'1.8.2','الكلوترالدهيد'),
    ('Produits végétaux ou d''origine végétale: Produits d''extraction du pin, notamment essence de térébenthine, colophane et ses dérivés',161,'1.8.2','المواد النباتية أو ذات أصل نباتي: مواد استخراج الصنوبر خاصة روح الربنتين و صمغ البطم و مشتقاته'),
    ('Produits végétaux ou d''origine végétale: Baume du Pérou',162,'1.8.2','المواد النباتية أو ذات أصل نباتي: بلسم'),
    ('Produits végétaux ou d''origine végétale: Urushiol (laque de chine)',163,'1.8.2','المواد النباتية أو ذات أصل نباتي: الاوروشيول ( لك الصين)'),
    ('Produits végétaux ou d''origine végétale: Plantes contenant des lactones sesquitérpéniques (notamment artichaut, arnica, chrysanthème, camomille, laurier noble, saussurea, frullania, bois de tulipier, armoise, dahlia)',164,'1.8.2','المواد النباتية أو ذات أصل نباتي: النباتات المحتوية على لكتونات سادس التربيني ( خاصة الخرشوف _ الارنيكا _ الأقحوان_ البابونج _الإكليل _ السوسوريا الفورولانيا, شجرة الزنبق , شيب الشيخ و الدهلية)'),
    ('Produits végétaux ou d''origine végétale: Primevère',165,'1.8.2','المواد النباتية أو ذات أصل نباتي: زهرة الربيع'),
    ('Produits végétaux ou d''origine végétale: Tulipe',166,'1.8.2','المواد النباتية أو ذات أصل نباتي: التوليب'),
    ('Produits végétaux ou d''origine végétale: Alliacées (notamment ail et oignon)',167,'1.8.2','المواد النباتية أو ذات أصل نباتي: الثوميات ( الثوم و البصل خاصة)'),
    ('Produits végétaux ou d''origine végétale: Farines de céréales',168,'1.8.2','المواد النباتية أو ذات أصل نباتي: دقيق الحبوب'),
    ('Rayonnements ionisants ',169,'2.1',' ﺍﻹﺷﻌﺎﻋﺎﺕ ﺍﻷﻳﻮﻧﻴﺔ'),
    ('Lésions chroniques du ménisque ',170,'2.10',' إصابات مزﻣﻨﺔ ﻟﻠﻐﻀﺮﻭﻑ ﺍﻟﻤﻔﺼﻠي '),
    ('Pression est supérieure à la pression atmosphérique ',171,'2.11',' ﺍﻷﻋﻤﺎﻝ ﺍﻟﻤﻨﺠﺰﺓ ﺩﺍﺧﻞ ﺍﻷﻭﺳﺎﻁ ﺍﻟﺘﻲ ﻳﻜﻮﻥ ﺿﻐﻄﻬﺎ ﺃﻋﻠﻰ ﻣﻦ ﺍﻟﻀﻐﻂ ﺍﻟﺠﻮﻱ'),
    ('Rayonnement thermique (affections oculaires)',172,'2.2','ﺍﻹﺷﻌﺎﻉ ﺍﻟﺤﺮﺍﺭﻱ (الإصابات العينية)'),
    ('Rayonnement thermique associé aux poussières ',173,'2.2 bis','ﺍﻹﺷﻌﺎﻉ ﺍﻟﺤﺮﺍﺭﻱ ﻭ ﺍﻟﻐﺒﺎﺭ ﻣﻌﺎ '),
    ('Particules en circulation dans les puits de mine de charbon (Lésions chroniques du segment antérieur de l''œil) ',174,'2.3','الجزيئات ﺍﻟﻤﺘﺤﺮﻛﺔ ﻓﻲ ﺁﺑﺎﺭ ﻣﻨﺎﺟﻢ ﺍﻟﻔﺤﻢ (ﺍﻻﺻﺎﺑﺎﺕ ﺍﻟﻤﺰﻣﻨﺔ ﻟﻠﺠﺰء ﺍﻻﻣﺎﻣﻲ ﻣﻦ ﺍﻟﻌﻴﻦ)'),
    ('Travaux éxecutés dans les mines',175,'2.4','الأشغال المنجزة داخل المناجم'),
    ('Bruits lésionnels (atteinte auditive)',176,'2.5','ﺍﻟﻀﺠﻴﺞ ﺍﻟﻤﻀﺮ (إصابات السمع)'),
    ('Vibrations et chocs transmis par certaines machines-outils, outils et objets et par les chocs itératifs du talon de la main sur des éléments fixes gestes et postures de travail ',177,'2.6',' ﺍﻻﺭﺗﺠﺎﺟﺎﺕ ﻭﺍﻟﺼﺪﻣﺎﺕ ﺍﻟﺼﺎﺩﺭﺓ ﻣﻦ ﺑﻌﺾ ﺍﻷﺩﻭﺍﺕ ﺍﻵﻟﻴﺔ ﻭﺍﻷﺩﻭﺍﺕ ﻭﺍﻷﺷﻴﺎء ﻭﻛﺬﺍ ﺑﺎﻟﺼﺪﻣﺎﺕ ﺍﻟﻤﺘﻜﺮﺭﺓ ﻟﻤﺆﺧﺮ ﺍﻟﻴﺪ ﻋﻠﻰ ﻋﻨﺎﺻﺮ ثاتبة'),
    ('Gestes et postures du travail ',178,'2.7','ﺑﻌﺾ ﺍﻟﺤﺮﻛﺎﺕ ﻭﻭﺿﻌﺎﺕ ﺍﻟﺠﺴﻢ ﺃﺛﻨﺎء العمل'),
    ('Vibrations de basses et moyennes fréquences transmises au corps entier ',179,'2.8',' ﺍﻟﻤﺰﻣﻨﺔ ﻟﻠﻌﻤﻮﺩ ﺍﻟﻔﻘﺮﻱ ﺍﻟﻘﻄﻨﻲ ﺍﻻﺭﺗﺠﺎﺟﺎﺕ ﺫﺍﺕ ﺍﻟﺘﺮﺩﺩ ﺍﻟﻤﻨﺨﻔﺾ ﻭ ﺍﻟﻤﺘﻮﺳﻂ ﺍﻟﻤﻨﻘﻮﻟﺔ ﺇﻟﻰ ﺍﻟﺠﺴﻢ ﻛﻠﻪ'),
    ('Manutention manuelle de charges lourdes ',180,'2.9',' ﺍﻟﻤﻨﺎﻭﻟﺔ ﺍﻟﻴﺪﻭﻳﺔ ﻟﻸﺣﻤﺎﻝ ﺍﻟﺜﻘﻴﻠﺔ (الإصابات ﺍﻟﻤﺰﻣﻨﺔ ﻟﻠﻌﻤﻮﺩ ﺍﻟﻔﻘﺮﻱ ﺍﻟﻘﻄﻨﻲ)'),
    ('Brucelloses professionnelles ',181,'3.1','البروسيلات'),
    ('Agents infectieux ou parasitaires contractées en milieu d''hospitalisation et d''hospitalisation à domicile (staphylocoques, pseudomonas aeroginosa, enterocoque, méningocoque, strepto béta-hémolytique, fièvre typhoϊde A et B, choléra, fièvre hémorragique, herpes, syphilis, gale, gonocoque)',182,'3.10','العناصر التعفنية ﺃﻭ الطفيلية ﺍﻟﺘﻲ ﻳﻤﻜﻦ ﺍﻟﺘﻌﺮﺽ ﻟﻬﺎ ﻓﻲ ﺍﻷﻭﺳﺎﻁ ﺍﻻﺳﺘﺸﻔﺎﺋﻴﺔ ﺃﻭ ﺃﺛﻨﺎء الاستشفاء بالمنزل '),
    ('Virus de l''hépatite B',183,'3.11','ﺍﻟﺘﻌﻔﻨﺎﺕ ﺍﻟﻤﻬﻨﻴﺔ ﺍﻟﻤﺼﺪﺭ ﻭ ﻓﻴﺮﻭﺳﺎﺕ ﺍﻻﻟﺘﻬﺎﺏ ﺍﻟﻜﺒﺪﻱ ﺃ ﻭ ﺏ ﻭﺝ ﻭ ﺩ ﻭ ﻩ. '),
    ('Virus des Hépatites A,B,C,D et E ',184,'3.11','ﺍﻟﺘﻌﻔﻨﺎﺕ ﺍﻟﻤﻬﻨﻴﺔ ﺍﻟﻤﺼﺪﺭ ﻭ ﻓﻴﺮﻭﺳﺎﺕ ﺍﻻﻟﺘﻬﺎﺏ ﺍﻟﻜﺒﺪﻱ ﺃ ﻭ ﺏ ﻭﺝ ﻭ ﺩ ﻭ ﻩ'),
    ('Amibes ',185,'3.12','ﺍﻟﻤﺘﻤﻮﺭﺍﺕ '),
    ('Rickettsies ',186,'3.13',' ﺍﻟﺮﻳﻜﺘﺴﻴﺎﺕ'),
    ('Rage professionnelle ',187,'3.14','ﺍﻟﻜﻠﺐ ﺍﻟﻤﻬﻨﻲ'),
    ('Ankylostomatose professionnelle',188,'3.15','داء الملقوة ﺍﻟﻤﻬﻨﻲ (ﻓﻘﺮ ﺍﻟﺪﻡ ﺍﻟﻤﺘﻮﻟﺪ ﻋﻦ ﺩﺍء ﺍﻟﻤﻠﻘﻮﺓ ﺍﻟﻌﻔﺠﻲ) '),
    ('Tularémie ',189,'3.16','التولارمية'),
    ('Animaux et leurs viscères',190,'3.17','الحيوانات و أحشائها'),
    ('Fruits sucrés et leurs résidus et leurs jus',191,'3.17','الفواكه الحلوة و مترسباتها'),
    ('Mines, bâtiments et chantiers',192,'3.17','المناجم تحت الأرض و أوراش البناء و أوراش الأشغال العمومية'),
    ('Périonyxis et onyxis ',193,'3.17','ﺍﻟﺘﻬﺎﺑﺎﺕ ﺍﻷﻇﺎﻓﺮ ﻭﻣﻨﺎﺑﺖ ﺍﻷﻇﺎﻓﺮ'),
    ('Mycoses cutanées ',194,'3.18','ﺍﻟﻔﻄﺎﺭﺍﺕ ﺍﻟﺠﻠﺪﻳﺔ'),
    ('Agents infectieux du groupe hantavirus',195,'3.19','ﺍﻟﺤﻤﻰ ﺍﻟﻨﺰﻓﻴﺔ ﻣﻊ ﻣﺘﺰﺍﻣﻨﺔ ﺍﻟﻜﻠﻲ ﻭ ﺍﻟﻌﻨﺎﺻﺮ ﺍﻟﺘﻌﻔﻨﻴﺔ ﻣﻦ ﻣﺠﻤﻮﻋﺔ ﻓﻴﺮﻭﺱ ﺍﻟﻬﺎﻧﺘﺎ '),
    ('Tétanos professionnel ',196,'3.2','ﺍﻟﻜﺰﺍﺯ ﺍﻟﻤﻬﻨﻲ '),
    ('Charbon professionnel ',197,'3.3','ﺍﻟﻔﺤﻢ ﺍﻟﻤﻬﻨﻲ'),
    ('Spirochétoses ',198,'3.4','الكوبالت'),
    ('Pasteurelloses ',199,'3.5','ﺃﻣﺮﺍﺽ ﺍﻟﺒﺎﺳﺘﻮﺭﻳﻼ '),
    ('Kératoconjonctivites virales ',200,'3.6','ﺍﻟﺘﻬﺎﺑﺎﺕ ﺍﻟﻘﺮﻧﻴﺔ ﻭﺍﻟﻤﻠﺘﺤﻤﺔ ﺍﻟﻔﻴﺮﻭﺳﻴﺔ'),
    ('Ornithose Psittacose ',201,'3.7','ﺍﻷﻣﺮﺍﺽ ﺍﻟﻄﻴﺮﻳﺔ ﻭﺍﻟﺒﺒﻐﺎﻧﻴﺔ'),
    ('Poliomyélites ',202,'3.8','ﺷﻠﻞ ﺍﻷﻃﻔﺎﻝ'),
    ('Bacilles tuberculeux et à certaines mycobactéries atypiques : Mycobacterium avium/intracellulaire, Mycobacterium kansasii, Mycobacterium xenopi, Mycobacterium marinum, Mycobacterium fortuitum ',203,'3.9','ﺍﻟﻌﺼﻴﺎﺕ ﺍﻟﺴﻠﻴﺔ ﻭ ﺑﻌﺾ ﺍﻟﻤﺘﻔﻄﺮﺍﺕ ﺍﻟﻐﻴﺮ ﻧﻤﻄﻴﺔ: ﺍﻟﻤﺘﻔﻄﺮﺓ  ﺍﻟﻄﻴﺮﻳﺔ ﺍﻟﺠﻮﺍﻧﻴﺔ ٬ ﺍﻟﻤﺘﻔﻄﺮﺓ ﺍﻟﻜﻨﺰﺍﺳﻴﺔ ﻭ ﺍﻟﻤﺘﻔﻄﺮﺓ ﺍﻟﻘﻴﻄﻤﻴﺔ ﻭ ﺍﻟﻤﺘﻔﻄﺮﺓ ﺍﻟﺒﺤﺮﻳﺔ ﻭ ﺍﻟﻤﺘﻔﻄﺮﺓ ﺍﻟﺘﺼﺎﺩﻓﻴﺔ '),
    ('Anhydrides d''acides volatils, notamment anhydrides maléique, phtalique, trimellitique tétrachlorophtalique, hexahydrophtalique, himique',204,'1.8.1 bis','استنشاق انهيدريد الأحماض المتبخرة خاصة: انهدريدات المالييك و الفتالية و ثالث الميليتية و رابع كلورو الفتالي و سادس الهيدرو فتالي و الهيمي'),
    ('Colles au cyanoacrylate',205,'1.8.1','الغراء بالسيانواكريلات'),
    ('Glutaraldéhyde',206,'1.8.1','الغلوترالدهيد'),
    ('Macrolides (notamment spiromycine et oléandomycine), de médicaments et de leurs précurseurs, notamment: glycols, salbutamol, pipérazine, cimétidine, hydralazine, hydralazine de l''acide nicotinique (isoniazide), chlorure d''acide de la phényl glycine, tétracylines, alpha-méthyl-dopa',207,'1.8.1','الماكفوليات خاصة سبيروميسين و الاوليندوميسين, الأدوية و السلائف, خاصة: الغليكول و السالبوتامول, بيبيرازين, السيميتيدين, الهيدرالازين, هيدرالازين حامض النيكوتينيك (إيزونيازيد ), حامض كلوريد فنيل الغليسين, التتراسكلين, ألفا كيثيل دوبا'),
    ('Travaux effectuées dans des milieux où la pression est supérieure à la pression atmosphérique',208,'2.12','الأعمال المنجزة في وسط يكون فيه الضغط أقل من الضغط الجوي و خاضع للتغييرات'),
    ('Poussières végétales: Préparation et manipulation du café vert, du thé, du soja, du tabac, du houblon, de l''orge',209,'1.8.1 bis','أغبرة النباتات: إعداد و مناولة البن الأخضر و الشاي و فول الصوجا و التبغ و الجنجل و الشعير')`,[],
    (tx, error) => {
      console.error("Error inserting values into PathType:", error
      );
    });
  }
} );
});

       // Vérification et insertion dans PathTab
       db.transaction(tx => {
       tx.executeSql('SELECT COUNT(*) AS count FROM PathTab', [], (tx, results) => {
        console.log('PHUDU');
        if (results.rows.item(0).count === 0) {
          tx.executeSql(`INSERT INTO PathTab (NTAB,IDPath) VALUES('1.1.1',259),
          ('1.1.1',260),
          ('1.1.1',125),
          ('1.1.1',13),
          ('1.1.1',365),
          ('1.1.1',89),
          ('1.1.1',257),
          ('1.1.1',124),
          ('1.1.1',263),
          ('1.1.10',231),
          ('1.1.10',269),
          ('1.1.10',101),
          ('1.1.10',57),
          ('1.1.10',370),
          ('1.1.11',43),
          ('1.1.11',417),
          ('1.1.11',322),
          ('1.1.12',346),
          ('1.1.12',347),
          ('1.1.12',412),
          ('1.1.12',354),
          ('1.1.12',201),
          ('1.1.12',382),
          ('1.1.12',151),
          ('1.1.12',343),
          ('1.1.13',240),
          ('1.1.13',297),
          ('1.1.13',195),
          ('1.1.14',52),
          ('1.1.14',402),
          ('1.1.14',279),
          ('1.1.15',55),
          ('1.1.17',345),
          ('1.1.17 bis',120),
          ('1.1.18',210),
          ('1.1.19',420),
          ('1.1.19',209),
          ('1.1.19',419),
          ('1.1.19 bis',35),
          ('1.1.19 bis',335),
          ('1.1.19 ter',61),
          ('1.1.19 ter',62),
          ('1.1.2',255),
          ('1.1.2',37),
          ('1.1.2',123),
          ('1.1.2',392),
          ('1.1.2',351),
          ('1.1.2',76),
          ('1.1.2',214),
          ('1.1.20',9),
          ('1.1.20',272),
          ('1.1.20',59),
          ('1.1.20',58),
          ('1.1.21',214),
          ('1.1.21',350),
          ('1.1.3',222),
          ('1.1.3',221),
          ('1.1.4',192),
          ('1.1.4',214),
          ('1.1.4',336),
          ('1.1.4',35),
          ('1.1.4',119),
          ('1.1.4 bis',48),
          ('1.1.4 bis',374),
          ('1.1.4 bis',139),
          ('1.1.4 ter',61),
          ('1.1.5',53),
          ('1.1.5',138),
          ('1.1.5',87),
          ('1.1.5',106),
          ('1.1.6',118),
          ('1.1.6',80),
          ('1.1.6',203),
          ('1.1.6',352),
          ('1.1.6',7),
          ('1.1.6',295),
          ('1.1.6',217),
          ('1.1.6',26),
          ('1.1.6',187),
          ('1.1.6',407),
          ('1.1.6',408),
          ('1.1.6',70),
          ('1.1.6',27),
          ('1.1.6',264),
          ('1.1.6',367),
          ('1.1.6',401),
          ('1.1.6',113),
          ('1.1.6',250),
          ('1.1.6',427),
          ('1.1.6',111),
          ('1.1.6',189),
          ('1.1.6',399),
          ('1.1.6',99),
          ('1.1.6',163),
          ('1.1.6',100),
          ('1.1.6',418),
          ('1.1.6',290),
          ('1.1.6',334),
          ('1.1.6',44),
          ('1.1.6',292),
          ('1.1.6',206),
          ('1.1.6',13),
          ('1.1.6',391),
          ('1.1.6',235),
          ('1.1.6',117),
          ('1.1.6',293),
          ('1.1.6',194),
          ('1.1.6',177),
          ('1.1.6',109),
          ('1.1.6',116),
          ('1.1.6',131),
          ('1.1.6',20),
          ('1.1.6',69),
          ('1.1.6',60),
          ('1.1.6',63),
          ('1.1.8 ter',64),
          ('1.1.9',280),
          ('1.2.1',261),
          ('1.2.1',265),
          ('1.2.10',77),
          ('1.2.10',248),
          ('1.2.10',348),
          ('1.2.10 ter',213),
          ('1.2.11',104),
          ('1.2.12',312),
          ('1.2.13',103),
          ('1.2.13',182),
          ('1.2.15',10),
          ('1.2.15',11),
          ('1.2.15',112),
          ('1.2.15',175),
          ('1.2.15',404),
          ('1.2.15',426),
          ('1.2.15',21),
          ('1.2.15',22),
          ('1.2.15',91),
          ('1.2.15',95),
          ('1.2.15',246),
          ('1.2.15',393),
          ('1.2.16',12),
          ('1.2.18',60),
          ('1.2.2',180),
          ('1.2.2',378),
          ('1.2.2',216),
          ('1.2.2 bis',403),
          ('1.2.20',368),
          ('1.2.3',4),
          ('1.2.3',313),
          ('1.2.4',3),
          ('1.2.5 bis',131),
          ('1.2.6',199),
          ('1.2.7',114),
          ('1.2.7',200),
          ('1.2.8',20),
          ('1.3.2',302),
          ('1.3.2',303),
          ('1.3.2',358),
          ('1.3.2',45),
          ('1.3.3',395),
          ('1.3.3',364),
          ('1.3.3',278),
          ('1.4.1',220),
          ('1.4.2',270),
          ('1.4.2',46),
          ('1.4.2',181),
          ('1.4.2',79),
          ('1.4.2',247),
          ('1.4.2',90),
          ('1.4.2',176),
          ('1.5.2',119),
          ('1.5.2',333),
          ('1.6.1',375),
          ('1.6.1',54),
          ('1.1.7',152),
          ('1.1.7',183),
          ('2.1',215),
          ('2.1',341),
          ('2.1',324),
          ('2.1',325),
          ('2.1',326),
          ('2.1',327),
          ('2.1',328),
          ('2.10',141),
          ('2.10',208),
          ('2.11',179),
          ('2.11',377),
          ('2.11',283),
          ('2.12',287),
          ('2.2',71),
          ('2.2 bis',317),
          ('2.4',268),
          ('2.5',5),
          ('2.6',41),
          ('2.6',394),
          ('2.6',30),
          ('2.6',281),
          ('2.6',282),
          ('2.7',387),
          ('2.7',388),
          ('2.7',338),
          ('2.7',129),
          ('2.7',132),
          ('2.7',171),
          ('2.7',39),
          ('2.7',173),
          ('2.7',359),
          ('2.7',172),
          ('2.7',174),
          ('2.7',386),
          ('2.7',384),
          ('2.7',383),
          ('2.7',360),
          ('2.7',385),
          ('3.1',47),
          ('3.1',140),
          ('3.1',153),
          ('3.1',239),
          ('3.1',130),
          ('3.1',143),
          ('3.1',275),
          ('3.1',316),
          ('3.1',340),
          ('3.1',25),
          ('3.1',29),
          ('3.1',241),
          ('3.1',276),
          ('3.1',277),
          ('3.1',339),
          ('3.1',349),
          ('3.10',50),
          ('3.10',299),
          ('3.10',80),
          ('3.10',42),
          ('3.10',127),
          ('3.10',133),
          ('3.10',148),
          ('3.10',285),
          ('3.10',288),
          ('3.10',344),
          ('3.10',236),
          ('3.11',67),
          ('3.11',6),
          ('3.11',15),
          ('3.11',68),
          ('3.11',75),
          ('3.11',135),
          ('3.12',168),
          ('3.14',329),
          ('3.15',13),
          ('3.16',371),
          ('3.17',186),
          ('3.19',188),
          ('3.19',369),
          ('3.1',372),
          ('3.2',390),
          ('3.3',74),
          ('3.3',271),
          ('3.3',321),
          ('3.3',73),
          ('3.4',97),
          ('3.4',273),
          ('3.5',232),
          ('3.5',226),
          ('3.6',85),
          ('3.6',204),
          ('3.6',83),
          ('3.6',84),
          ('3.6',205),
          ('3.7',301),
          ('3.7',146),
          ('3.7',145),
          ('3.8',228),
          ('3.9',413),
          ('3.9',414),
          ('3.9',411),
          ('1.1.6 bis',60),
          ('1.1.6 ter',60),
          ('1.1.7',255),
          ('1.1.7',2),
          ('1.7',72),
          ('1.7',33),
          ('1.1.8',104),
          ('1.1.8 bis',335),
          ('1.1.8 bis',35),
          ('1.1.8 ter',60),
          ('1.1.9',96),
          ('1.1.9',98),
          ('1.1.10',80),
          ('1.1.10',56),
          ('1.1.11',104),
          ('1.1.11',80),
          ('1.1.12',196),
          ('1.1.12',252),
          ('1.1.12',32),
          ('1.1.12',306),
          ('1.1.12',61),
          ('1.1.12',212),
          ('1.1.12',191),
          ('1.1.13',31),
          ('1.1.13',190),
          ('1.1.13',211),
          ('1.1.13',296),
          ('1.1.13',128),
          ('1.1.13',94),
          ('1.1.13',416),
          ('1.1.13 bis',61),
          ('1.1.14',256),
          ('1.1.14 bis',61),
          ('1.1.16',55),
          ('1.1.17',120),
          ('1.1.17 bis',61),
          ('1.1.18',417),
          ('1.2.1',396),
          ('1.2.1',167),
          ('1.2.1',309),
          ('1.2.1',18),
          ('1.2.1',24),
          ('1.2.1',230),
          ('1.2.2',379),
          ('1.2.4',223),
          ('1.2.4',102),
          ('1.2.3',3),
          ('1.2.5',289),
          ('1.2.5',105),
          ('1.2.5',214),
          ('1.2.5',150),
          ('1.2.5',193),
          ('1.2.6',198),
          ('1.2.6',197),
          ('1.2.6',229),
          ('1.2.6',105),
          ('1.2.6',357),
          ('1.2.7',184),
          ('1.2.8',105),
          ('1.2.8',214),
          ('1.2.8',335),
          ('1.2.8',35),
          ('1.2.8 bis',66),
          ('1.2.9',400),
          ('1.2.9',310),
          ('1.2.10',93),
          ('1.2.10',353),
          ('1.2.10',152),
          ('1.2.10',105),
          ('1.2.10 bis',105),
          ('1.2.10 bis',214),
          ('1.2.10 bis',335),
          ('1.2.10 bis',35),
          ('1.2.11 bis',335),
          ('1.2.11 bis',35),
          ('1.2.13',267),
          ('1.2.13',170),
          ('1.2.13',3),
          ('1.2.14',254),
          ('1.2.14',169),
          ('1.2.14',182),
          ('1.2.14',105),
          ('1.2.14',3),
          ('1.2.15',36),
          ('1.2.15',1),
          ('1.2.15',92),
          ('1.2.15',77),
          ('1.2.16',426),
          ('1.2.16',11),
          ('1.2.16',36),
          ('1.2.16',2),
          ('1.2.17',335),
          ('1.2.17',35),
          ('1.2.17',86),
          ('1.2.17',214),
          ('1.2.17',234),
          ('1.2.19',335),
          ('1.2.19',35),
          ('1.2.19',86),
          ('1.2.20',108),
          ('1.2.20',214),
          ('1.2.20',126),
          ('1.2.21',214),
          ('1.2.21',14),
          ('1.2.21',335),
          ('1.2.21',35),
          ('1.2.22',104),
          ('1.2.22',107),
          ('1.2.22',88),
          ('1.2.22 bis',131),
          ('1.2.22 bis',61),
          ('1.2.22 bis',415),
          ('1.2.23',355),
          ('1.2.23',405),
          ('1.2.23',406),
          ('1.2.23',311),
          ('1.2.23',266),
          ('1.3.1',209),
          ('1.3.2',335),
          ('1.3.2',35),
          ('1.3.2',214),
          ('1.3.3',19),
          ('1.4.2',251),
          ('1.4.2',110),
          ('1.4.2',119),
          ('1.4.2',72),
          ('1.4.2',426),
          ('1.4.2',33),
          ('1.4.2',11),
          ('1.5.2',214),
          ('1.5.1',214),
          ('1.5.2',35),
          ('1.5.3',214),
          ('1.5.3',81),
          ('1.5.4',214),
          ('1.5.4',417),
          ('1.5.4',81),
          ('1.5.4',335),
          ('1.5.4',35),
          ('1.5.5',154),
          ('1.6.2',214),
          ('1.6.2',86),
          ('1.6.2',335),
          ('1.6.2',35),
          ('1.6.2',373),
          ('1.6.2',137),
          ('1.6.2',65),
          ('1.6.3',423),
          ('1.6.3',335),
          ('1.6.3',35),
          ('1.6.3',81),
          ('1.6.3',332),
          ('1.6.3',214),
          ('1.7',426),
          ('1.7',249),
          ('1.8.1',335),
          ('1.8.1',35),
          ('1.8.1',192),
          ('1.8.1 bis',49),
          ('1.8.1 bis',137),
          ('1.8.2',209),
          ('2.1',16),
          ('2.1',17),
          ('2.1',43),
          ('2.1',80),
          ('2.1',202),
          ('2.1',71),
          ('2.1',61),
          ('2.3',82),
          ('2.5',178),
          ('2.7',389),
          ('2.7',366),
          ('2.7',361),
          ('2.7',40),
          ('2.8',342),
          ('2.8',323),
          ('2.9',342),
          ('2.9',323),
          ('2.11',284),
          ('2.12',286),
          ('2.12',207),
          ('3.1',381),
          ('3.1',307),
          ('3.1',300),
          ('3.1',331),
          ('3.1',144),
          ('3.1',298),
          ('3.1',155),
          ('3.1',13),
          ('3.1',318),
          ('3.1',8),
          ('3.1',253),
          ('3.1',127),
          ('3.1',294),
          ('3.1',330),
          ('3.1',236),
          ('3.1',245),
          ('3.1',227),
          ('3.1',233),
          ('3.1',34),
          ('3.4',134),
          ('3.4',237),
          ('3.4',115),
          ('3.4',398),
          ('3.4',38),
          ('3.4',397),
          ('3.4',291),
          ('3.4',122),
          ('3.4',28),
          ('3.9',409),
          ('3.9',380),
          ('3.9',277),
          ('3.9',315),
          ('3.9',410),
          ('3.9',305),
          ('3.9',185),
          ('3.10',219),
          ('3.10',238),
          ('3.10',51),
          ('3.10',149),
          ('3.10',78),
          ('3.10',121),
          ('3.10',262),
          ('3.10',320),
          ('3.10',304),
          ('3.10',424),
          ('3.10',428),
          ('3.10',147),
          ('3.11',159),
          ('3.11',142),
          ('3.11',136),
          ('3.11',157),
          ('3.11',158),
          ('3.11',160),
          ('3.11',162),
          ('3.11',165),
          ('3.11',166),
          ('3.11',425),
          ('3.11',218),
          ('3.11',308),
          ('3.11',314),
          ('3.11',258),
          ('3.11',319),
          ('3.11',362),
          ('3.11',164),
          ('3.11',156),
          ('3.11',161),
          ('3.11',363),
          ('3.11',376),
          ('3.11',421),
          ('3.11',422),
          ('3.13',337),
          ('3.13',225),
          ('3.13',224),
          ('3.17',274),
          ('3.18',242),
          ('3.18',244),
          ('3.18',243),
          ('3.19',356),
          ('1.2.15',23)
          `
          ,[],(tx, error) => {
            console.error("Error inserting values into PathType:", error);
          });

          
        }
      });})
      
  return "Database setup complete";};

// Appelle la fonction setupDatabase pour initialiser
// Fetch data function
export const fetchPathTypes = async () => {
  const db = await openDatabase();
  return new Promise((resolve, reject) => {
    db.transaction(tx => {
      tx.executeSql(
        'SELECT * FROM PathType',
        [],
        (tx, results) => {
          const items = [];
          for (let i = 0; i < results.rows.length; i++) {
            items.push(results.rows.item(i));
          }
          resolve(items);
        },
        (tx, error) => {
          reject(error);
        }
      );
    });
  });
};
export  { openDatabase };